### ISSUE TITLE
Semantic highlight determined only based on the first element of the scope

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1007]
ATM we use only the first matched scope to determine the face. Consider the following scopes: 

```
11 1 -> (lsp--semantic-highlighting-find-face ["storage.modifier.static.java" "variable.other.definition.java" "meta.definition.variable.java" "meta.class.body.java" "meta.class.java" "source.java"])
23 1 -> (lsp--semantic-highlighting-find-face ["storage.modifier.static.java" "entity.name.function.java" "meta.function-call.java" "meta.method.body.java" "meta.method.java" "meta.class.body.java" "meta.class.java" "source.java"])
```

There is no way to match these two scopes to "Static Variable" and "Static Function" face.

It is not clear to me whether we should alter  `lsp-semantic-highlighting-faces` to have multiple regexps and match the scope only if all the regexp are matching some of the scope elements or we should change lsp--semantic-highlights to return multiple faces (one per each scope element) and then apply all of the faces one after another. 

cc @sebastiansturm

**Comment by sebastiansturm** [comment]
I'd probably go with multiple regexps (though if we require them all to match, we may quickly assemble a load of face matchers that are specific to a single language server backend), or perhaps replace the regexp entry with an arbitrary predicate function (in which case lsp mode could provide some convenience functions to construct commonly used predicates).

Since AST elements corresponding to a particular `scopeIndex` will always be associated with the same set of scopes, I wouldn't want to apply multiple faces to their overlays; that seems like unneeded overhead to me. If the multiple-regexp/arbitrary-predicate approach turns out not to be good enough, and we decide to combine faces, I'd rather have lsp precompute an aggregate face (though in that case we'd have to make sure those faces are updated whenever the user switches color themes). What do you think?

**Comment by yyoncho** [comment]
The multi regex solution fits well with the current approach but we might hit MxN problem. Consider that we have const/enum/class/field/method/interface and we have deprecated and static attributes. I would want all static to be italic and all deprecated to be underlined - this makes 24 faces. 

I think it will be fine to start simple(multiple regexp) and see how it goes. The feature is not official yet and might never hit the lsp spec so there is no point to invest a lot of effort in it.
