### ISSUE TITLE
lsp-go: changing imports style is difficult

### ISSUE THREAD

**Issue by jmhodges** [emacs-lsp/lsp-mode#1153]
**To Reproduce**

Type an import line like `import "testing"`. Go to add another import by typing `(` and then RET before the quotation mark in `"testing"`. Notice that the `(` gets added to the `"testing"` link and the RET opens up the browser window for the docs of the `testing` package.

**Expected behavior**

The RET adding a newline after the `(` and before the `"testing"`.

**Which Language Server did you use**
gopls with lsp-go

**OS**
macOS

**Comment by psanford** [comment]
Yeah I see this behavior too. That's pretty annoying.

**Comment by seagle0128** [comment]
The issue was confirmed. The import strings are treated as document links (buttons in Emacs), and `mouse-2` and `RET` actions will browse the links. IMO `RET` should be replaced by `M-RET` or `s-RET`. @yyoncho Your opinion?

BTW, my workaround is not using `RET` after `(`, `goimports` will format automatically  while saving the buffer.

**Comment by yyoncho** [comment]
> IMO RET should be replaced by M-RET or s-RET. @yyoncho Your opinion?

Make sense.

**Comment by seagle0128** [comment]
@yyoncho the PR is committed. Please review. Thanks!
