### ISSUE TITLE
[lsp--calculate-root]lsp-find-session-folder should be placed before of lsp--suggest-project-root

### ISSUE THREAD

**Issue by honmaple** [emacs-lsp/lsp-mode#1233]
**Describe the bug**
```
code
├── .git/
└── suffix/
    ├── go.mod
    ├── go.sum
    ├── suffix.go
    └── suffix_test.go
```
When I open `suffix.go`，abort
```
LSP :: Your workspace root is xxx/code, but your module root is xxx/code/suffix. Please add xxx/code/suffix as a workspace folder.
```
then I use `lsp-workspace-folders-add` add `xxx/code/suffix` folder, but the problem still happened

**Which Language Server did you use**
lsp-go, gopls

**OS**
macos 10.14.6

Another suggestion, don't use `(unless lsp-auto-guess-root ...)`

**Comment by yyoncho** [comment]
What  lsp-auto-guess-root setting do you use?

**Comment by honmaple** [comment]
I use `(setq lsp-auto-guess-root t)`

**Comment by yyoncho** [comment]
@honmaple this setting overrides any other info(e. g. session folders) and if you want to to use it you should make sure that the autoguess function always returns the correct value. I recommend against using it unless you are familiar with how lsp-mode and projectile or project .el work.

In this case in order to solve your issue, you should add `.projectile` in suffix directory(in case you are using projectile). I am sure how to achieve the same for `project.el`.
