### ISSUE TITLE
Can't trigger nested highlighting

### ISSUE THREAD

**Issue by muirdm** [emacs-lsp/lsp-mode#1239]
When a highlighted region has nested highlightable regions, moving the cursor to the smaller highlightable regions doesn't shrink the highlight. You can only get the small regions to trigger if you move outside the big highlight and then move directly to the small highlight.

![highlight](https://user-images.githubusercontent.com/11356572/70565523-2d9b4580-1b47-11ea-9275-836870424c8c.gif)

It seems like we need to re-query for highlighting even if the cursor is currently in a highlit region.

**Comment by yyoncho** [comment]
Yes, unless we call that behaviour a feature. Marking it as a bug for now.

**Comment by leungbk** [comment]
One problem that remains is the following:

0) point is on some highlighted text
1) an asynchronous edit from the server pushes preceding text forward so that an already-highlighted region now ends up at point
2) if we were to ask the server for highlights with point at the pushed-forward text, the server ought to respond with a different set of highlights.

But 2) won't happen with PR #1647.

**Comment by muirdm** [comment]
I still see some issues with the after #1647:
![highlight](https://user-images.githubusercontent.com/11356572/90325864-d8190300-df35-11ea-9214-9c47ef53a931.gif)
