### ISSUE TITLE
Opening a program file creates too many buffers

### ISSUE THREAD

**Issue by Ayush1325** [emacs-lsp/lsp-mode#1410]
So, I started using lsp mode in emacs. It works quite well, at least with the languages I use. Anyway, the one problem I have is that every time I open a python file, It automatically creates 2 or 3 buffers after connecting to the lsp server. One of them is a python interpreter and others are pretty much random(although none are ever my actual file). So I have to go and switch everytime. So well, I was just wondering if that's supposed to happen? And is there a fix? Just for reference, here are the buffer lists of extra buffers:
- lsp-log
- pyls
- pyls::stderr
- Python-Help (The interactive python shell which opens)

[Here](https://github.com/Ayush1325/dotfiles/blob/master/.emacs.d/configuration.org) is my emacs config if that is required

**Comment by yyoncho** [comment]
A buffer is not always backed by a file. In this case, these buffers are needed for the communication between lsp-mode and the server. You may configure emacs to skip those buffers when you are switching. The last one is created by something else.

**Comment by Ayush1325** [comment]
Ok, the last one is teh only one I have a problem with, others kinda stay out of the way. Any idea what it can be though, coz it started appearing after I switched from elpy to lsp?

**Comment by yyoncho** [comment]
The only place containing "Python-" prefix in my emacs setup is in org-mode. You may look for what is the major mode in this buffer and then add a function to start debugging when the mode is started. This way you will find the corresponding call stack and who is starting it

**Comment by crockeo** [comment]
Sorry to necro this after it's been closed, but I think the `*Python-Help*` buffer may be produced by `lsp-mode`, albeit indirectly.

* Normally in `python-mode` you can disable `eldoc-mode` and to prevent the buffer from appearing.
* When using `lsp-mode`, and in particular when `lsp-managed-mode` is truthy, [this codepath](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L3152-L3155) is executed.
* It sets `eldoc-mode` to active, and triggers `python-mode` eldoc implementation to produce `*Python-Help*`.

I'm too new to Emacs and elisp to know exactly what the solution should be, but I thought I'd report but I think the problem is.

**Comment by Ayush1325** [comment]
Thanks, was currently playing around with spacemacs and the problem doesn't seem to be there. Will try to modify my original config later if I find a way.

**Comment by crockeo** [comment]
This is what I've done in the meantime:

```elisp
;; Intercepting calls to py-help-at-point so that we never have to see
;; *Python-Help* ever again.
(defun intercept-call (oldfn &rest args))
(advice-add 'py-help-at-point
            :around #'intercept-call)
```

This prevents `python-mode` from opening the `*Python-Help*` buffer while hovering on a symbol. @yyoncho does `lsp-mode` need `eldoc-mode` enabled in the codepath I linked above to function? If not it may be worth changing the functionality to respect the user's `eldoc` settings.

**Comment by Ayush1325** [comment]
Thanks, will try it.
