### ISSUE TITLE
How to setq server's variable when using tramp?

### ISSUE THREAD

**Issue by FirstLoveLife** [emacs-lsp/lsp-mode#1411]
I'm really happy with lsp-mode's tramp integration! But I don't know how to setq server's variable via tramp, here is my config:
```
(lsp-register-client
   (make-lsp-client :new-connection (lsp-tramp-connection "/home/firstlove/projects/github/ccls/build/ccls")
                    :major-modes '(c++-mode)
                    :remote? t
                    :server-id 'ccls-remote))
```
Where can I add `(setq ccls-sem-highlight-method 'overlay)` and `(ccls-use-default-rainbow-sem-highlight)` to let remote ccls know?

**Comment by yyoncho** [comment]
You set this variable like any normal variable but in order to make it work you should copy all of the sections from the ccls configuration - https://github.com/MaskRay/emacs-ccls/blob/e5cc4c3e6f40c9c9f0f53e99154c08018eb36944/ccls.el#L158 

I am closing the issue but you may use it for further questions.
