### ISSUE TITLE
Why it uses lv-message

### ISSUE THREAD

**Issue by behollder** [emacs-lsp/lsp-mode#1499]
Hello all.
Why it uses lv-message and not eldoc-message?
lv-message adds new line-window above echo area with twitch. With eldoc-message it will not happen and eldoc-message with eldoc-box can show signature help message at point.

![image](https://user-images.githubusercontent.com/1114246/76212661-a4f97780-6211-11ea-8ccd-2147ab827b86.png)
![image](https://user-images.githubusercontent.com/1114246/76232844-f9135480-622f-11ea-8ad8-3cca29b9f3fc.png)

**Comment by yyoncho** [comment]
FYI eldoc-box is spin of lsp-ui-doc. We use eldoc-message to show hover info and lv-message to show signature at the point so you can see both at the same time. In the future, we will do a posframe implementation like the one on the screen but using posframe directly.

Note that, often the signature info is multiline which when using eldoc-message might cause blinking as you type because if a mode shows a message it will override the our eldoc-message. This is much more disturbing than the blinking 2 times - at the start and at the end. If someone is looking for less noise he/she could disable autoactivation and request the signature on demand. This is not a problem with the hover info because most of the time we manage to keep it single line.

**Comment by behollder** [comment]
> FYI eldoc-box is spin of lsp-ui-doc. We use eldoc-message to show hover info and lv-message to show signature at the point so you can see both at the same time. In the future, we will do a posframe implementation like the one on the screen but using posframe directly.
> 
> Note that, often the signature info is multiline which when using eldoc-message might cause blinking as you type because if a mode shows a message it will override the our eldoc-message. This is much more disturbing than the blinking 2 times - at the start and at the end. If someone is looking for less noise he/she could disable autoactivation and request the signature on demand. This is not a problem with the hover info because most of the time we manage to keep it single line.

Agree with you and great to hear about plans for the future. I'm not an expert in lisp and lsp-mode src code but I modified code for self and got all like on screenshots in my question. And it seems work great. This is temporary solution for me.

Thank you for an answer with explain.

**Comment by yyoncho** [comment]
> This is temporary solution for me.

As part of this bug, I will make display signature function configurable so you could make it work without changing the source. Additionally, I will file a bug in lsp-ui for the full implementation which will also include coordination with lsp-ui-doc itself since both windows could hide each other.
