### ISSUE TITLE
Refactoring suggestion: Merge all code into a single file

### ISSUE THREAD

**Issue by phst** [emacs-lsp/lsp-mode#153]
Currently the `lsp-mode` code is spread out across several files, with lots of cross-references between these files. In general it's good practice to keep files short, but in the case of Emacs Lisp there's a strict correspondence between files and packages, and due to the per-file nature of byte-compilation, self-contained code can't easily be split between files. One outcome is e.g. https://github.com/emacs-lsp/lsp-mode/commit/2fc278a07bba25cac518d20d62d0c4cee74fda38, where I had to forward-declare multiple functions and variables.
Also the bulk of the code is in lsp-methods.el anyway, with the other files being rather short, so I think merging all the files (except lsp-flycheck.el) shouldn't decrease readability.

**Comment by vibhavp** [comment]
While starting lsp-mode, I wanted to replicate the file structure of `erc`. If not into a single file, a lot of code does needs to be consolidated (`lsp-send.el` and `lsp-receive.el` come to mind).

**Comment by yyoncho** [comment]
@vibhavp 
Are we going to address this PR?

I am asking this question since https://github.com/emacs-lsp/lsp-mode/issues/376 will be breaking change and I could keep the old code in lsp-*.el so until we move all of the lsp clients to the new infrastructure. So instead of making the old code work in 2 modes(multi server/legacy single server) I could move all of the code in a new file and make it work only for multi server. Then when we move all extension to use the new infrastructure, we can delete the old code. What do you think?
