### ISSUE TITLE
Company-capf breaks snippet's filling

### ISSUE THREAD

**Issue by tpadioleau** [emacs-lsp/lsp-mode#1642]
**Describe the bug**
Cannot go to next field of a snippet when it is filled with result from `company-capf`.

**To Reproduce**
`lsp-start-plain.el`
```elisp
;;; lsp-start-plain.el --- LSP mode quick starter      -*- lexical-binding: t; -*-

;; Copyright (C) 2018 Ivan Yonchovski

;; Author: Zhu Zihao <all_but_last@163.com>
;; Keywords: languages

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is a helper to start a minimal lsp environment.
;; To use this, start your Emacs with "emacs -q" and load this file.

;; It will install `lsp-mode', `lsp-ui' with their dependencies to start a
;; minimal lsp environment.

;; And it forces Emacs to load `.el' files rather than `.elc' files
;; for more readable backtrace.

;;; Code:

(require 'package)

(setq debug-on-error t)

(let* ((package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("gnu" . "https://elpa.gnu.org/packages/")))
       (no-byte-compile t)
       (package-user-dir (expand-file-name (make-temp-name "lsp-tmp-elpa")
                                           user-emacs-directory))
       (custom-file (expand-file-name "custom.el" package-user-dir))
       (pkg-list '(lsp-mode yasnippet company)))

  (package-initialize)
  (package-refresh-contents)

  (mapcar (lambda (pkg)
            (unless (package-installed-p pkg)
              (package-install pkg))
            (require pkg))
          pkg-list)

  (add-hook 'prog-mode-hook 'yas-minor-mode)
  (add-hook 'prog-mode-hook 'lsp)

  (setq company-backends '((company-capf)))

  (add-hook 'kill-emacs-hook `(lambda ()
                                (delete-directory ,package-user-dir t))))

(provide 'lsp-start-plain)
;;; lsp-start-plain.el ends here
```

Write the following code in the file `main.cpp`
```c++
#include <array>

int main()
{
  std::array
}
```
1) Execute `company-capf` on `std::array`,
2) select first choice (should be something like `std::array<typename Tp, std::size_t _Nm>`), it should have two fields to fill,
3) fill first field, `typename Tp`, by selecting `double` with the help of `company-capf`,
4) I cannot fill second entry `std::size_t _Nm`, it is printed `[yas] Committing snippets. Action would destroy a protection overlay.`.

**Expected behavior**
After filling a field from `company-capf`, be able to switch to next field of the current snippet.

**Which Language Server did you use**
`clangd` (same with `ccls`)

Thanks

**OS**
Ubuntu 18.04

**Error callstack**
no error but a warning `[yas] Committing snippets. Action would destroy a protection overlay.` after selecting `double`

**Comment by kiennq** [comment]
@tpadioleau Can you try setting `yas-inhibit-overlay-modification-protection` to `t`?
https://github.com/emacs-lsp/lsp-mode/issues/1451#issuecomment-592397738

**Comment by tpadioleau** [comment]
@kiennq Yes setting the variable to `t` allows to go to next field. This is a good starting point.

It seems to me that this [line](https://github.com/emacs-lsp/lsp-mode/blob/922b6d295105e92245b0c6633af8c80f6d782fe6/lsp-mode.el#L4408) is responsible of `yas` warning.

To check that assumption, I modified exit function from:
```elisp
(text-edit
  (delete-region (point-at-bol) (point))
  (insert prefix-line)
  (lsp--apply-text-edit text-edit))
```
to
```elisp
(text-edit
  (setq tmp-point (point))
  (goto-char (point-at-bol))
  (search-forward prefix-line (point-at-eol))
  (delete-region (point) tmp-point)
  (lsp--apply-text-edit text-edit))
```
This may not optimized and always reliable but it gives the idea: only delete what is inside the snippet's field. It seems to do the trick in the case I mentionned with `std::array`.

**Comment by kiennq** [comment]
@tpadioleau 
There're several reasons that we cannot avoid modifying the outside of snippet's field:
- The completion prefix considered by `major-mode` (in your case, `c++-mode`) and language server can be different. We should prefered language server prefix, however Emacs API required us to declare the prefix immediately (and cannot be changed later), thus calling to language server to get the prefix is difficult and can be perf problem. So to fix that, we just put `major-mode` defined prefix to Emacs and later do necessary adjudgment by ourselves. That will ensure both perf and make sure that we always replace the completion candidate at the right place.
That approach has a down-turn: since Emacs is using the `major-mode` prefix, which can be outrage different from what language server thinks, Emacs will replace the completion candidate at the place that is not so correct. So, we have to restore the buffer state by using `delete-region` from `bol` to `point` and replaced it with `prefix-line`, that's the easiest and cover all edge cases of restoring the buffer to the state that was sent to language server.
- The `text-edit` that returned from server **can** contains the range out of snippet field. This depends on the language server but it's a completely valid behavior. So even if we can somehow avoid the first `delete-region`, this can still be hit. Typescript language server is one of the server that's doing that.
- Moreover, there're also `additional-text-edits`, that's also from language server that can change the buffer content any where. For example, automatically insert missing header or `use namespace`.

With that, I don't think we can limit the change inside the snippet field alone.
Setting `yas-inhibit-overlay-modification-protection` is the best now, I think.

@yyoncho Should we add this into FAQ or just quietly set `yas-inhibit-overlay-modification-protection` in `lsp-managed-mode` buffers?

**Comment by yyoncho** [comment]
> @yyoncho Should we add this into FAQ or just quietly set yas-inhibit-overlay-modification-protection in lsp-managed-mode buffers?

Let's modify it silently when auto-configure is on - if someone does like it, they could turn it off.

**Comment by tpadioleau** [comment]
>     * The `text-edit` that returned from server **can** contains the range out of snippet field. This depends on the language server but it's a completely valid behavior. So even if we can somehow avoid the first `delete-region`, this can still be hit. Typescript language server is one of the server that's doing that.
>
>     * Moreover, there're also `additional-text-edits`, that's also from language server that can change the buffer content any where. For example, automatically insert missing header or `use namespace`.

I understand, actually I didn't know that LSP coud have this kinf of non-local effects on the buffer.
