### ISSUE TITLE
Cannot rename symbol when eslint is configured

### ISSUE THREAD

**Issue by jkdufair** [emacs-lsp/lsp-mode#1659]
I've enabled eslint alongside typescript with by by setting `lsp-eslint-server-command` in my startup. When I do this and try to rename a symbol via `lsp-rename`, I get a timeout (maybe because it's trying to send the rename to both backends?).

Glad to try and fix this if it is indeed a bug. Pointers would be welcome.

**Comment by yyoncho** [comment]
Thank you for willing to fix it by yourself!

> Glad to try and fix this if it is indeed a bug. Pointers would be welcome.

This is a bug in lsp--send-request-async - generally, we support calling two backends - we merge the response and it is all good. The bug is that if one of the servers returns an error we hang because as you can see in lsp--create-async-callback we return when the number of responses = number of servers. But when this never happens when one of the servers fails.

Solution1: fix lsp--create-async-callback to count both errors and successful responses.

Solution2: rework lsp-mode to use `deferred`/`emacs-promise` - https://github.com/emacs-lsp/lsp-mode/issues/1471
