### ISSUE TITLE
lsp-keymap-prefix not working

### ISSUE THREAD

**Issue by haoyuan80s** [emacs-lsp/lsp-mode#1672]
Hi, I set prefix for lsp-command-keymap  by `(setq lsp-keymap-prefix "C-S-l")`.
With _describe variable_ i can see:
![image](https://user-images.githubusercontent.com/9064146/81486197-0933ba00-9208-11ea-8e14-af8fcdfcea55.png)
But all the lsp functions are still have `s-l` as prefix:
![image](https://user-images.githubusercontent.com/9064146/81486167-d8ec1b80-9207-11ea-8b9a-104221685497.png)
How set the prefix correctly?

**Comment by Lenbok** [comment]
It is counter-intuitive how that doesn't work. I think it depends on when you call the `setq`. In my init I have:
```
(use-package lsp-mode
  :commands lsp
  :init
  (setq lsp-keymap-prefix "C-c l")
  :config
  (define-key lsp-mode-map (kbd "C-c l") lsp-command-map)
  (require 'lsp-clients)
  :hook (lsp-mode . lsp-enable-which-key-integration))
```
The `define-key` gets the actual commands working with the desired prefix, and the `setq` ensures that the `which-key` integration is using the correct prefix. 

The lsp-mode docs show customization of the prefix by putting the `setq` before (outside) the `use-package` so that probably works as well, although it seems wrong to have it outside of the `use-package`.

**Comment by yyoncho** [comment]
the issue is that you should set the prefix before lsp-mode has been loaded and I am not quite sure how to achieve that with use-package. 

>  :config
>  (define-key lsp-mode-map (kbd "C-c l") lsp-command-map)

This works fine too.

I am closing the issue but it could be used for further discussions.

**Comment by haoyuan80s** [comment]
Yes, the key is "set the prefix before lsp-mode has been loaded ". 

My problem was that I loaded _ccls_ before _lsp-mode_. Seems that _ccls_ loaded _lsp-mode_ (without set the prefix). I fixed it by adding ":after lsp" in when loading ccls package: `(use-package ccls :after lsp)`. Then, I am able to set the prefix in the "natural way":
```
(use-package lsp-mode
    :init (setq lsp-keymap-prefix "C-c l")
```

**Comment by phillord** [comment]
I know that this issue has been closed, but I wonder whether it was worth revisiting. I have just hit the same problem caused by loading `lsp-ui` before `lsp`. Moving `(setq lsp-keymap-prefix "blah")` to top-level doesn't solve this problem.

This could be implemented by having a `lsp-remap-prefix` function and documented this as the main mechanism. This could also be added to the `lsp-keymap-prefix` customize code also, as I guess this won't work in without a restart.

Happy to send a PR if this would seem to be reasonable.

**Comment by yyoncho** [comment]
@phillord what about using setter for the defcustom?

**Comment by phillord** [comment]
@yyoncho Not sure I understand. It doesn't have one at the moment. As far as I can see, we'd just need to call

````
  (define-key map (kbd lsp-keymap-prefix) lsp-command-map)
````

and then re-run the which-key integration. So a simple function which wraps that lot up, updated documentation and updating the defcustom to use this as a set function. Is that enough, or am I missing something. Can change this into a PR if wanted.

**Comment by yyoncho** [comment]
I meant instead of having this as part of a separate function it seems like having it part of the setter might be more convenient. 

``` emacs
(defcustom lsp-keymap-prefix "s-l"
  "lsp-mode keymap prefix."
  :group 'lsp-mode
  :type 'string
  :package-version '(lsp-mode . "6.3")
  :set (lambda (sym val)
         ;; unbind old value
         ;; bind new value, update which-key, etc.
         ))
```

**Comment by phillord** [comment]
I'd go the other way. Have this as a function, then call that function as the `:set` from `defcustom`. That way it would also work for people not using custom. There isn't a convienient way to call `defcustom` settters that I know of.

**Comment by kflu** [comment]
> It is counter-intuitive how that doesn't work. I think it depends on when you call the `setq`. In my init I have:
> 
> ```
> (use-package lsp-mode
>   :commands lsp
>   :init
>   (setq lsp-keymap-prefix "C-c l")
>   :config
>   (define-key lsp-mode-map (kbd "C-c l") lsp-command-map)
>   (require 'lsp-clients)
>   :hook (lsp-mode . lsp-enable-which-key-integration))
> ```
> 
> The `define-key` gets the actual commands working with the desired prefix, and the `setq` ensures that the `which-key` integration is using the correct prefix.
> 
> The lsp-mode docs show customization of the prefix by putting the `setq` before (outside) the `use-package` so that probably works as well, although it seems wrong to have it outside of the `use-package`.

Even if I do this, `C-c l` is still not registered as the binding. Only if I put 

      (define-key lsp-mode-map (kbd "C-c l") lsp-command-map)

Outside `use-package` after all the `use-package`s did it work. 

I still prefer to put `define-key` inside `use-package`, so does that mean I have some other kind of conflicts going on in my init.el?
