### ISSUE TITLE
Changes in after-change-function can break lsp's error display

### ISSUE THREAD

**Issue by aaronjensen** [emacs-lsp/lsp-mode#1704]
**Describe the bug**
When a change is made in an `after-change-function`, lsp's error checking does not properly respect that change which leaves errors that are not errors visible. These don't go away until the buffer is saved.

It's certainly possible that this is a flycheck issue. 

Downstream report: https://github.com/jcs-elpa/auto-rename-tag/issues/9

**To Reproduce**

Clone and follow instructions: https://github.com/aaronjensen/lsp-auto-rename-repro

**Expected behavior**
The error should disappear when there is no longer an error

**Which Language Server did you use**
typescript

**OS**
macOS

**Error callstack**
No error

**Comment by yyoncho** [comment]
> https://github.com/aaronjensen/lsp-auto-rename-repro

This link is dead.

**Comment by aaronjensen** [comment]
@yyoncho sorry, forgot to make it public, please try again

**Comment by yyoncho** [comment]
As per docs 

> Buffer changes made while executing the `before-change-functions'
don't call any before-change or after-change functions.
That's because `inhibit-modification-hooks' is temporarily set non-nil.

This means that there is no way for lsp-mode to detect the change and send it to the server. The fix for that is in auto-rename-tag to avoid doing any changes in after/before change hooks and execute then after the hooks have finished. One way to do that is to stash the changes and execute them in post-command hook.

**Comment by aaronjensen** [comment]
@yyoncho thanks! I just read that as well and got it working by firing the change in a timer afterwards, but a post-command hook seems to make even more sense.
