### ISSUE TITLE
company-mode should not hide the dialog when lsp-mode does not have the time handle the call

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1894]
At this point `lsp-mode` returns `nil` to `company-mode` when the server was not
able to respond and the user has started typing. This is a workaround of capf
being synchronous. This triggers hiding of completion dialog which later it
displayed again if there is completion result for the longer prefix. We should
eliminate that.

Potential fixed:

1. Throwing something that company-mode expects and it will be treated like "keep
   the dialog open"
2. Implementing traditional(not capf) async company backend. I suspect that the
   described issue does not exist in that case.
3. We may try to return the previous available result. Not sure if this will
   work but we do that on other places like eldoc-mode to avoid blinking.

cc @dgutov @kiennq

**Comment by kiennq** [comment]
We can indeed returns previous value in this case.
@dgutov Do you think that will fix the issue?

**Comment by yyoncho** [comment]
I just want to mention that this issue is hurting the usability of posframe solutions because they are a bit slower in showing/hiding the completion items. At the same time, the solutions with overlays that company offers are not compatible with overlays. So if lsp-mode wants to support lsp protocol flawlessly with we should have working posframe solution.

**Comment by kiennq** [comment]
> I just want to mention that this issue is hurting the usability of posframe solutions because they are a bit slower in showing/hiding the completion items.

I'm aware that create new frame can be slow but posframe showing/hiding is fairly fast since we don't have to recreate the posframe everytime?

**Comment by dgutov** [comment]
> We can indeed returns previous value in this case.

This should work. It's an interesting hack, actually.

Option 2 probably isn't going to help (I never optimized for this scenario together with based frontends, and the overlay-based one hides/shows very quickly), but it's an area that could be improved. And without a major redesign of the loop, internally the change is probably going to behave at lot like your suggestion. ;-)

API-wise, option 1 would be ideal, but I think it needs some support in the core as well (else it would break `M-x completion-at-point`, and you probably care about that, right?). You might as well wait for an async convention in completion tables instead (so that `company-capf` turns it into option 2). Maybe file an Emacs feature request to remind the maintainers about this need.

**Comment by yyoncho** [comment]
> (else it would break `M-x completion-at-point`, and you probably care about that, right?).

Yes. Generally, we should be blocking in completion-at-point and not aborting the computation on user input.

> Maybe file an Emacs feature request to remind the maintainers about this need.

I will do that. Are you aware of any plans to move completion stuff in elpa package?

**Comment by yyoncho** [comment]
> I'm aware that create new frame can be slow but posframe showing/hiding is fairly fast since we don't have to recreate the posframe everytime?

@kiennq it is fast, but also it should wait for the server to return so the blinking is noticeable. IMO this causes noise

**Comment by dgutov** [comment]
> we should be blocking in completion-at-point and not aborting the computation on user input

Right. Your abort-on-input code should check the value of `non-essential`, and only abort if the value is `t`.

> Are you aware of any plans to move completion stuff in elpa package?

No such plans, and `minibuffer.el` is somewhat essential to Emacs. But who knows. It should be possible, one way or another.
