### ISSUE TITLE
Invalid severity level

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#1961]
- GNU Emacs 28
- macOS Catalina
- [pyright](https://github.com/emacs-lsp/lsp-pyright)

Example:
```python
class Foo:
    '''test
    '''
    def __init___(self):
        pass

skldasdj
```
`flycheck-current-errors` is 
```elisp
(#s(flycheck-error #<buffer main.py> lsp "/Users/xxx/src/mspyls/subdir/src/main.py" 16 5 "\"skldasdj\" is not defined" error nil nil 16 13)
#s(flycheck-error #<buffer main.py> lsp "/Users/xxx/src/mspyls/subdir/src/main.py" 13 19 "\"self\" is not accessed" lsp-flycheck-info-unnecessary nil nil 13 23))
```

`(flycheck-count-errors flycheck-current-errors)` is `((lsp-flycheck-info-unnecessary . 1) (error . 1))`

I think `lsp-flycheck-info-unnecessary` should be `info`.

**Comment by yyoncho** [comment]
Why do you think that this is invalid level? In order to support Diagnostic.tag we generate the corresponding flycheck levels.

**Comment by seagle0128** [comment]
The default levels are error, warning, info. It's hard to handle the misc customized levels for other packages, e.g. doom-modeline.

**Comment by yyoncho** [comment]
For doom-modeline I would suggest to use `lsp-modeline-diagnostics-mode` which is more powerful since it can show the errors for the project, session or for the current file.

@cpitclaudel, at this point we are dynamically creating flycheck levels in order to customize the overlays. Our input is `(lsp-diagnostic-level [lsp-diagnostics-tag])` and we generate flycheck level from this, e. g. `(info [unnecessary])` we will generate level `lsp-flycheck-info-unnecessary` which has the `info` face merged with the face attributes corresponding to `unnecessary` tag. This dynamic level is causing trouble for the clients because it does not inherit the original `info` level.

One way to fix is to allow overriding the overlay for the diagnostic when creating the diagnostic itself, the alternative is change the counting code. WDYT?

**Comment by cpitclaudel** [comment]
Hmm, interesting issue.  I guess it didn't pop up in the error list because sorting by priority will DTRT given that priority orders.  I was going to suggest that we could introduce some sort of `parent` property of error levels that the counting code could use, but then I realized that we already have it as `:compilation-level` :)  Changing the counting code to use that seems reasonable to me. What do you both think?  (and if you agree, should we add a new function or modify the existing one?)

**Comment by cpitclaudel** [comment]
Thanks for looping me in, btw ^^

**Comment by yyoncho** [comment]
> Changing the counting code to use that seems reasonable to me. What do you both think?

This makes sense to me.

> (and if you agree, should we add a new function or modify the existing one?)

I think it is your call. ATM you return conses (level . count) if you start
returning (compilation-level . count) new function seems to be the better
option for backward compatibility reasons.

**Comment by seagle0128** [comment]
It does make sense to me. Keeping the conventional levels, and counting with others. Thanks for looking into it.

**Comment by cpitclaudel** [comment]
> If you start
returning (compilation-level . count) new function seems to be the better
option for backward compatibility reasons.

Ok, let's roll with that ^^ @seagle, do you want to write the new counting function?

**Comment by seagle0128** [comment]
> > If you start
> returning (compilation-level . count) new function seems to be the better
> option for backward compatibility reasons.
> 
> Ok, let's roll with that ^^ @seagle, do you want to write the new counting function?

Let's try to do it.

**Comment by yyoncho** [comment]
I am closing this since there is nothing to do on lsp-mode side.

**Comment by seagle0128** [comment]
But, pls let me know the rules. And the rules won't be changed anymore? @cpitclaudel @yyoncho

**Comment by cpitclaudel** [comment]
I'm not sure what you mean, but I'm happy to help with the implementation.  The idea would be to implement a separate function for counting errors that counts them by compilation-level, not by level.

**Comment by seagle0128** [comment]
@cpitclaudel originally I count errors, warnings and info of flycheck.  Now I have to count others like `lsp-flycheck-info-unnecessary`, but I don't know all types here. Appreciate it if you can provide the function or example.

**Comment by cpitclaudel** [comment]
You want to check `flycheck-error-level-compilation-level`: it will return 0, 1, or 2 for info, warning, or error: `(flycheck-error-level-compilation-level 'warning) ⇒ 1`.

**Comment by seagle0128** [comment]
@cpitclaudel thanks for the advice!
