### ISSUE TITLE
web-mode,when open .scss file, lsp auto load html-ls instead of css-ls

### ISSUE THREAD

**Issue by petsgre** [emacs-lsp/lsp-mode#2044]
![image](https://user-images.githubusercontent.com/22208613/89887054-3e351b80-dc00-11ea-9410-9f4475918b19.png)

**Comment by ericdallo** [comment]
Yeah, we start the html-ls after opening a `web-mode`: https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-html.el#L180
I'm not sure how to fix that as web-mode is for `html` files too, right?

**Comment by yyoncho** [comment]
We can write activation functions which check the extension type when the major mode is web-mode.

**Comment by leungbk** [comment]
> We can write activation functions which check the extension type when the major mode is web-mode.

Would it be better to always rely on extension alone? If I open a file with a long line when `global-so-long-mode` is enabled, the server will not stay on since no server corresponds to the `so-long` major mode.

**Comment by yyoncho** [comment]
I was considering this in the past. The issue here is when you have file, with no extension with a header like `#!/bin/python`. The file will be opened in python-mode but it won't have an extension. 

I think that in vscode activation happens on language where the language is calculated based on filename and maybe the content. The actication of a langauge server can happen also based on a file in the root(e. g. pom.xml). IMO what we can do is combine both major mode and extension. We already kind of have that mapping in `lsp-language-id-configuration` .

**Comment by billop** [comment]
Is the way to do this as an end user by registering custom servers to implement that sort of logic ourselves?

**Comment by yyoncho** [comment]
@billop you can use `with-eval-after-load`. FTR lsp-activate-on is what we are going to use in the future.

**Comment by billop** [comment]
Idk why but my workaround stopped working for me. If anyone has lsp working with web-mode please let me know how you did it.

**Comment by yyoncho** [comment]
@billop try `M-: (lsp-buffer-language)`. Also, check if lsp-clients has your registration. Try changing the priority of the client to 0 in case different client is starting.

**Comment by billop** [comment]
It seems like the culprit is `lsp-language-id-configuration`. Web-mode is associated with html, and there is no extension checking for css. Once I prepended `(".*\\.css$" . "css")` it worked with my custom client since `lsp-activate-on` calls `lsp-buffer-language` which relies on `lsp-language-id-configuration`.

**Comment by billop** [comment]
Now I'm experiencing something very weird. My workaround for javascript by editing `lsp-language-id-configuration` stopped working. `(lsp-buffer-language)` correctly outputs `"javascript"`, but opening a `.js` file which enable `web-mode` nonetheless activates `html-ls`. This is even when I have `(delete '(web-mode . "html") lsp-language-id-configuration)` in my init.el.
