### ISSUE TITLE
Disable flycheck checkers when the lsp checkers are enabled

### ISSUE THREAD

**Issue by michaelpj** [emacs-lsp/lsp-mode#2207]
(I asked this on gitter, and I didn't get much response, so I thought I'd report it here nonetheless.)

The default flycheck checkers are often obsoleted by `lsp-mode`. But they're usually still enabled, which is confusing. 

For example, the default Haskell checkers are slow and give spurious errors, so it's a much better experience to turn them off when using `lsp-haskell`.

Can we/should we do this automatically?

**Comment by ericdallo** [comment]
I didn't get it, lsp checkers use flycheck checkers, right @yyoncho ?

**Comment by yyoncho** [comment]
My gut feeling is that we should not disable them mainly due to the fact that it will most likely break users' configs and such actions are usually causing confusion. What about documenting how to disable checkers in the corresponding language-specific guides? 

cc @cpitclaudel

**Comment by michaelpj** [comment]
> My gut feeling is that we should not disable them mainly due to the fact that it will most likely break users' configs and such actions are usually causing confusion.

Yes, we rather want some way to tell flycheck that we're providing a checker *for this buffer*. The disabled checker setting is global, so we probably shouldn't set that.

> What about documenting how to disable checkers in the corresponding language-specific guides?

We can certainly do this regardless, I'm planning to add something to the `lsp-haskell` README regardless. But it would be nice if it "just worked".

**Comment by brotzeit** [comment]
The lsp-mode flycheck checker is enabled by default right ?

**Comment by cpitclaudel** [comment]
> The disabled checker setting is global, so we probably shouldn't set that.

It can be made buffer-local, so that's a possibility, but see below:

> The lsp-mode flycheck checker is enabled by default right ?

Exactly: when do other checkers run if the lsp one is enabled?  There's no chaining from LSP to other checkers, so other checkers shouldn't run, right?

**Comment by michaelpj** [comment]
Hmm, maybe I'm misunderstaning how the flycheck checkers work and I should investigate more.

What I've observed is that the non-lsp default checkers *do* run (at least for Haskell), but maybe there's a bug there.

**Comment by michaelpj** [comment]
Just recording what I've seen:
- `flycheck-verify-setup` says that the `lsp` checker is explicitly suggested, but that `haskell-stack-ghc` "could run if selected".
- In `Messages` I see `Suspicious state from syntax checker haskell-stack-ghc: ...` (the error isn't important), which suggests that it *did* run at some point.

I don't know how this could happen: maybe somehow the `haskell-stack-ghc` checker runs before the `lsp` one gets registered as the favoured one?

**Comment by yyoncho** [comment]
Is there anything for lsp-mode here?

**Comment by michaelpj** [comment]
If the answer turns out to be "the lsp-client code for the language should do something to disable the checkers", then there might be some work for us to update those. I don't know yet.

**Comment by michaelpj** [comment]
Some progress: I think this may actually be some kind of race. I only see the output from the wrong checker the first time I open a Haskell file. So my working hypothesis is that if something in `lsp-mode` has not been loaded yet, then we can sneak in an execution of the default flycheck checkers before we override it.

**Comment by yyoncho** [comment]
This is caused by the fact that lsp-mode won't disable other checkers until the server is initialized because we don't know if the server supports diagnostics. I think that this will be solved if you manually force lsp-mode checker with code like that:


``` emacs-lisp
(add-hook 'haskel-mode-hook 'lsp-diagnostics-mode)
```

**Comment by numkem** [comment]
I've been having the same problem with Go. Sometimes I get `flycheck` results and sometimes it's empty. `lsp-treemacs` always shows the right number of errors so `gopls` is returning them normally.

**Comment by yyoncho** [comment]
Seems like the fix should be to disable other checkers if they are running but I am not sure how to do that with flycheck, there are several methods for disabling a checker.

**Comment by cpitclaudel** [comment]
Is this a race condition like "flycheck starts running checker, then lsp starts and realizes a the server supports diagnostics, then lsp disable flychecks but results still get reported?"

That would be a bug in Flycheck; it shouldn't report errors after it's been disabled.  It thought it didn't.  Can someone confirm whther I understand the issue correctly?

In any case maybe LSP could disable other checkers preemptively and then reenable them if the no diagnostics backend is available?
Still I'd like to understand the issue better.

**Comment by yyoncho** [comment]
> Is this a race condition like "flycheck starts running checker, then lsp starts and realizes a the server supports diagnostics, then lsp disable flychecks but results still get reported?"

Your understanding is correct except for the fact that we do not explicitly disable other checkers but we just set ourselves as the flycheck-checker like this:

```
  (setq-local flycheck-checker 'lsp)
```


> In any case maybe LSP could disable other checkers preemptively and then reenable them if the no diagnostics backend is available?

This will work. Fixing current flow will be easier though.

**Comment by cpitclaudel** [comment]
Right, this makes sense.  Flycheck gets a batch of results and it doesn't confirm that the checker that it got results from is the right one.

Would it be enough to call `flycheck-stop` in addition to your `setq`?

**Comment by yyoncho** [comment]
@cpitclaudel thank you.

@michaelpj can you test https://github.com/yyoncho/lsp-mode/commit/5766dfb6671fa8516348bcd4981a277a52715d61 ?

**Comment by michaelpj** [comment]
@yyoncho That commit fixes the issue for me!

**Comment by yyoncho** [comment]
PR at #2225

@cpitclaudel thank you for the help!

**Comment by ericdallo** [comment]
> The result is that we have duplicated error notifications:

Not sure this could be considered duplicate, as the modeline usually is configured to show all the project errors, not the buffer only

**Comment by memeplex** [comment]
Ok, you got a point there, didn't know about that. Still it seems like flycheck is a subset of lsp diagnostics, isn't it? In case it's not adding anything beyond lsp diagnostics, is disabling flycheck-mode when  lsp-modeline-diagnostics-mode is enabled, instead of merely stopping it, out of the question?

**Comment by ericdallo** [comment]
Not sure, I like my modeline showing the project diagnostics and the current buffer one on the same time

**Comment by memeplex** [comment]
Yes, I've been playing with it for a moment and you're right, I'd just seen lsp working in one file until then.

It's likely the way doom-modeline is showing it that feels weird:

* Different faces for both counts.
* Counts are as apart as possible.
* One shows the "stop icon" while the other doesn't.

But it's understandable since support for flycheck is built in doom-modeline.

Anyway, I use minions and I don't have  lsp-modeline-diagnostics-mode as a minions-direct, yet it's showing in the modeline, is it writing to the modeline in a non-standard way?

**Comment by ericdallo** [comment]
That's I agree, we could try to improve the UI somehow, not sure how though.

It uses the `global-mode-string` which AFAIK is the correct way of doing it.

**Comment by memeplex** [comment]
I think that's for more ad hoc messages, presumably for the final user to tweak, but a minor mode should use the lighter: https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Minor-Modes.html

**Comment by memeplex** [comment]
I can't say I fully agree with the reasoning because the idea is after all that the user is in charge, every other minor mode author could have just said the same and it would be chaos, specifically that can be said of the likes of flymake and flycheck in this context.

Although I do understand that you likely want to cater new users that are on emacs "distros" with alternative modelines that silence minor modes by default and so would be left on their own without some visual cue, still the onus is on the authors of said modelines to provide alternative visualizations to those they decided to hide.

Also an argument can be made that the only point of  `lsp-modeline-diagnostics-mode` is to show something so it's of no use to have it enabled but hidden at the same time.

That said, there still is `lsp-modeline-diagnostics-enable`, although I can't conveniently toggle it on and off from the modeline.
