### ISSUE TITLE
lsp-mode diagnostics sometimes disappear on making an unrelated change

### ISSUE THREAD

**Issue by raxod502-plaid** [emacs-lsp/lsp-mode#2262]
**Describe the bug**
In some circumstances, making an innocuous change to a buffer will cause diagnostic messages to disappear from elsewhere onscreen.

**To Reproduce**
In `init.el`:

```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'lsp-mode)
(straight-use-package 'flycheck)
(straight-use-package 'go-mode)

(add-hook 'go-mode-hook #'lsp)

(setenv "GO111MODULE" "auto")
```

In `main.go`:

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello, world!")
}
```

Now start Emacs and edit `main.go`. Navigate to after the closing paren of `fmt.Println("Hello, world!")` and backspace. This will produce a diagnostic (underlined in red):

![image](https://user-images.githubusercontent.com/69264599/96298102-bde7b980-0fa6-11eb-9523-51e167167ea4.png)

Next, navigate to the empty line above `func main() {` and insert a space character. For some reason, this causes the diagnostic to disappear:

![image](https://user-images.githubusercontent.com/69264599/96298151-d526a700-0fa6-11eb-894a-73e46d9f4a64.png)

Deleting the space character does not cause the diagnostic to reappear. However, re-inserting and re-removing the closing paren does cause it to reappear (even if the space was not deleted).

**Expected behavior**
Diagnostics should remain onscreen when making other changes, unless the other changes cause the language server to no longer be able to produce those diagnostics (e.g. introducing a syntax error).

**Which Language Server did you use**
gopls

**OS**
macOS 10.15.7

**Version information**
GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, Carbon Version 162 AppKit 1894.6) of 2020-09-11
golang.org/x/tools/gopls v0.5.1
    golang.org/x/tools/gopls@v0.5.1 h1:AF3Uh7HF08SZpKFfgJO6zfF3bbxyDXWqdkK4kMXiQ1o=
```
b92ab5a39b987e4fe69317b9d9fda452300baf20 dash.el
83bfe8b5f9bcd3653dbea383776183c6d36841ac emacsmirror-mirror
78ab7a85c08222cd15582a298a364774e3282ce6 epl
1814209e2ff43cf2e6d38c4cd476218915f550fb f.el
cd8e0a280c9980c8c7ce31fd2458df7fd81a0acf flycheck
1109d1b777feb63650436934ecc1cca8ad0f1078 gnu-elpa-mirror
d17d21060b16a77f9ee28ff453e674225acbf1b1 go-mode.el
fff8c43f0e03d5b98deb9f988522b839ce2ca253 ht.el
112e689f75b59398d8eca79ac6562dca12b8a959 hydra
b299c78897cc307f9d5521927376fbd06a26f123 let-alist
7c6ace2d9e4ca4e7230c5989ae47991c7db61c7f lsp-mode
cf6403186119cd3d25adc702845f969071060e20 markdown-mode
c2c21a3cf3bc42293efb65536f5b784efa66e5bf melpa
76ba7415480687d05a4353b27fea2ae02b8d9d61 pkg-info
43ba8b563bee3426cead0e6d4ddc09398e1a349d s.el
2daa167bec1c7566d662d48613a94453536b524a spinner
5d046ad09413f3aba6198229e392cdd3f07e77ee straight.el
```

**LSP log**
https://gist.github.com/raxod502-plaid/26f97631ad3efae121f2701e7546798b

**Comment by jakejx** [comment]
I did some investigation as I was also experiencing this with gopls. I believe this is caused by the interaction of two things:
1. gopls does not re-publish diagnostics, after a buffer change, if there are no changes in the diagnostics.
2. The default lsp setting `lsp-diagnostic-clean-after-change` causes the diagnostics to be deleted after a buffer change.

Thus, after when `flycheck-buffer` runs again, based on the users `flycheck-check-syntax-automatically`, Flycheck will re-run and see that there are no diagnostics.

The solution is either to set `lsp-diagnostic-clean-after-change to `nil` or use the Flymake backend. From what I can tell Flymake saves the current diagnostics as overlays and does not update them unless the callback function is triggered (which is only called when new diagnostics are published).

I am not sure what other language servers do about diagnostics, do they publish whenever there is a buffer change or only when the diagnostics change? I think at least this behaviour for gopls should be documented so that other users do not run into this issue.

**Comment by s-kostyaev** [comment]
> or use the Flymake backend

I use flymake backend on daily basis and also see diagnostics disappeared sometimes. Not sure exactly, but looks like it disappears after file save.

**Comment by yyoncho** [comment]
I changed the default of lsp-diagnostic-clean-after-change to nil. It is what vscode is doing too(although they don't have 0.5 seconds delay). I have few ideas on how to fix that delay and the errors misplacement but that would result in lsp flycheck being incompatible with other backends...
