### ISSUE TITLE
Support newer versions of vscode-html-languageserver

### ISSUE THREAD

**Issue by leungbk** [emacs-lsp/lsp-mode#2286]
@jsmestad mentioned this on Gitter. ~This should be an upgrade over the languageserver-bin we currently support, though it doesn't look like it puts an executable in any place that would reasonably be expected to be in `PATH`; the file structure we get after `npm i -g vscode-html-languageservice` seems similar to that of the `angular-language-service` we currently support~

~https://github.com/Microsoft/vscode-html-languageservice~

I misunderstood the distinction between vscode's `languageserver`s and `languageservice`s. If the upstream `vscode-*-languageserver-bin`s get updated, all we would need to do is to support the new settings.

**Comment by jsmestad** [comment]
I'd love to tackle this if anyone has any ideas how to get a binary out of the new service. 

Also it looks like there are several other language services from MS we can update too like css

**Comment by leungbk** [comment]
> I'd love to tackle this if anyone has any ideas how to get a binary out of the new service.

After installing, it looks like we get some `.js` and `.ts` files that we can run with Node. In `lsp-angular.el` we have to do something similar.

**Comment by SebastienWae** [comment]
Isn't `Microsoft/vscode-html-languageservice` already one of the language service being use by `vscode-langservers/vscode-html-languageserver`?

**Comment by leungbk** [comment]
> Isn't `Microsoft/vscode-html-languageservice` already one of the language service being use by `vscode-langservers/vscode-html-languageserver`?

Right now [we seem to be using](https://github.com/emacs-lsp/lsp-mode/blob/997b38f877a09aa9d1646e00381c62694f3f8808/clients/lsp-html.el#L174) `vscode-html-languageserver-bin`, which [hasn't been updated in a while](https://github.com/vscode-langservers/vscode-html-languageserver-bin).

**Comment by SebastienWae** [comment]
My bad I thought it was using `vscode-langservers/vscode-html-languageserver` directly.

I made [SebastienWae/vscode-html-ls-bin](https://github.com/SebastienWae/vscode-html-ls-bin) to replace `vscode-html-languageserver-bin` then, it's building the html language server directly form the vscode repo.

**Comment by jsmestad** [comment]
@leungbk @yyoncho how would be go about replacing the existing LSP clients with these new ones?

**Comment by SebastienWae** [comment]
I sent an email to the [vscode-langservers](https://github.com/vscode-langservers) maintainer, since it would be easier to keep using the same project. Hopefully I'll have an answer quickly.

@jsmestad I don't think it's a good idea to use the same binary name, however if you do not want to wait you can uninstall the current ones, clone my repos (with the `--recursive` flag), edit the `bin` parameter in the `package.json` then `npm run compile` and `npm install -g /path/to/the/repo`.

**Comment by jsmestad** [comment]
> I sent an email to the [vscode-langservers](https://github.com/vscode-langservers) maintainer, since it would be easier to keep using the same project. Hopefully I'll have an answer quickly.
> 
> @jsmestad I don't think it's a good idea to use the same binary name, however if you do not want to wait you can uninstall the current ones, clone my repos (with the `--recursive` flag), edit the `bin` parameter in the `package.json` then `npm run compile` and `npm install -g /path/to/the/repo`.

Yeah I think I could also use a symlink to get things working as-is in lsp-mode. Do you know how to find out what LSP features these new binaries support compared with the old ones? I wouldn't be surprised to see new functionality we can take advantage of

**Comment by SebastienWae** [comment]
Here are **some** of the updates I have noted.

HTML:
- custom data support
- semantic selection
- details and link for ARIA attributes
- MDN Reference link
- tag rename on type

CSS:
- custom data support
- semantic selection
- better support for file/module import
- better documentation
- MDN Reference link
- deprecation warning
- completion with semicolon

JSON:
- custom data support
- semantic selection

**Comment by jsmestad** [comment]
@leungbk Could we get support for these new language servers in lsp-mode? 🙏

**Comment by leungbk** [comment]
@alexdima and @aeschli, would it be possible to see an update of `vscode-*-languageserver-bin`? Thanks.

**Comment by SebastienWae** [comment]
@leungbk Microsoft has nothing to do with the [github/vscode-langservers](https://github.com/vscode-langservers) and all the `vscode-*-languageserver-bin`, @alexdima and @aeschli are on the contributors list because the repos are just mirror of the `vscode` repo.

I tried contacting @DeltaEvo the maintainer of [github/vscode-langservers](https://github.com/vscode-langservers) a few months back but I didn't get any answer.

If you want a more recent version you can use my repos:
https://github.com/SebastienWae/vscode-json-ls-bin
https://github.com/SebastienWae/vscode-html-ls-bin
https://github.com/SebastienWae/vscode-css-ls-bin
I havn't updated them for the past 2 months but it's still better.

I'm planning on automating the extraction and testing from the `vscode` repo next month,  when it's done if you want I can then transfere everything to [github/emacs-lsp](https://github.com/emacs-lsp/) to be sure that it will be maintained for the foreseeable future.

**Comment by yyoncho** [comment]
> I'm planning on automating the extraction and testing from the `vscode` repo next month, when it's done if you want I can then transfer everything to [github/emacs-lsp](https://github.com/emacs-lsp/) to be sure that it will be maintained for the foreseeable future.

Sounds good.

**Comment by RKBK** [comment]
@SebastienWae 

I just ran into issues with errors from the css-ls with a simple scss file like the following:
tmp.scss
```
.header {
  width: 50%;
  margin: 0 auto;

  &-link {
    color: blue;
  }
}
```

After some guidance from @yyoncho , we got to the conclusion that we needed probably the new version of the css-ls that you have built. 

This is just to say that if you manage to find the time to do the automation work you mentioned, so that this can be maintained in emacs-lsp, I would be very grateful!

For now, I can probably use your css-ls manually.

**Comment by Aaronzinhoo** [comment]
@RKBK Just ran into an issue with completion in `scss` also when trying to use the `use` import statement as well. I am guessing that a new up to date server will fix this since `use` is newer and the vscode server is about 3 years old now without any updates.

**Comment by jsmestad** [comment]
@SebastienWae inquiring minds would like to know 😉 did you make any more progress?

**Comment by yyoncho** [comment]
I am considering adding the option to use the servers as packaged by vscode/vscodium itself - e. g. `node /usr/share/code/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js` will be sufficient to run the html language server from vscode.

**Comment by jcs090218** [comment]
Same, any progress on this? 😕

**Comment by Aaronzinhoo** [comment]
What exactly is needed for this? If it's a larger task maybe we could break it down to make it more manageable to address. I don't have a lot of time but I also really want this feature and wouldn't mind working on it.

**Comment by yyoncho** [comment]
closing in favor of https://github.com/emacs-lsp/lsp-mode/issues/3395 .
