### ISSUE TITLE
Question about `flycheck-idle-change-delay`

### ISSUE THREAD

**Issue by Yevgnen** [emacs-lsp/lsp-mode#243]
Hi, I have a question about flycheck in lsp-mode.

When `lsp-mode` is enabled, `flycheck-idle-change-delay` seem does not take effect. Every time I type a char, syntax is checked immediately. Is this related to `lsp-mode`? If so, is that possible for me to adjust this? Thanks in advance.

**Comment by vibhavp** [comment]
AFAIK, flycheck works by invoking the syntax checker after an idle delay and parsing its output. In LSP's case, any textual changes to the file are sent instantly to the language server. The server will perform its own checks, and then send them to Emacs, which `lsp-mode` relays to flycheck. Since the `lsp-mode` checker does not invoke any command to perform syntax checking, the `idle-change-delay` variable is never used.

**Comment by Yevgnen** [comment]
Thanks for the information. So is that mean there’s no way to deal with
this? Checks are too often for me though...
