### ISSUE TITLE
some suggestions 

### ISSUE THREAD

**Issue by samrayleung** [emacs-lsp/lsp-mode#245]
### Symbol Highlight
In my humble opinion, the result of `Symbol Highlighting` in `lsp-mode`  is horrible:
![lsp-highlight-yellow](https://user-images.githubusercontent.com/14180681/35180391-61a8a36c-fdea-11e7-9958-2322f97d5478.png)
So I chage the `lsp-face-highlight-textual` to:
```elisp
(set-face-attribute 'lsp-face-highlight-textual nil
		    :background "#666" :foreground "#ffffff"
                   )
``` 
Now, it looks like:
![lsp-hightlight-zenburn 666](https://user-images.githubusercontent.com/14180681/35180402-cadf3c74-fdea-11e7-9ecf-20ffe604e2c7.png)

![lsp-highlight-tomorrow 666](https://user-images.githubusercontent.com/14180681/35180386-53c01f50-fdea-11e7-8fa9-91b6ab01773f.png)
I think this looks better. 
### lsp-format-buffer
After I call `lsp-format-buffer`,  the cursor position will jump to the begining-of-buffer, which doesn't save the location of point. The source code of `lsp-format-buffer` is 
``` elisp
(defun lsp-format-buffer ()
  "Ask the server to format this document."
  (interactive)
  (let ((edits (lsp--send-request (lsp--make-request
				   "textDocument/formatting"
				   (lsp--make-document-formatting-params)))))
    (lsp--apply-text-edits edits)
    ))
```
I try to simply wrap this function with `save-excursion` and make a PR, but I could not get it work as expected. I am not familiar with `lsp-mode` and have no idea why `save-excursion` couldn't work , so I try to post some feedback here. It will be great to save the cursor position when call `lsp-format-buffer`

**Comment by terlar** [comment]
It is not necessarily true that that other face will look good, it totally depends on the theme of the user therefore the recommended way for setting default faces is to inherit from some of the standard faces provided by emacs if there is some that somewhat matches the semantics, for example in this case inheriting from `highlight` might be a good idea or potentially `match` or `isearch` but the first one seems more intuitive.

But in this case I understand it might be hard since there are three different highlights:
- textual
- read
- write

And if you want to distinguish between those. Perhaps inherit from `success`, `warning`, `error` or `highlight`, `success`, `warning`. Then more themes would look good out of the box.

**Comment by bsed** [comment]
Error (use-package): lsp-mode/:init: Invalid face: lsp-face-highlight-textual
  2                                                                                                     ┃  2 Error (use-package): org/:config: Invalid version syntax: ‘’ (must start with a number)
