### ISSUE TITLE
`clangd` is adding incorrect headers

### ISSUE THREAD

**Issue by gdkrmr** [emacs-lsp/lsp-mode#2503]
As discussed in https://github.com/syl20bnr/spacemacs/issues/12936, `clangd` tries to add headers automatically by default. The problem is that these normally are incorrect. This can be done by setting `lsp-clients-clangd-args` to `"--header-insertion=never"`. Do you think that this should be the default?

**Comment by yyoncho** [comment]
@sebastiansturm, @danielmartin, any thoughts?

**Comment by sebastiansturm** [comment]
`--header-insertion=never` is what I'm using, so I certainly wouldn't object to that being the default. Though my reason for using that setting was not so much wildly incorrect headers, but rather the fact that I don't want header insertion without me explicitly asking for it.
When doing that (using the 'missing include' fixits), headers are correct in my experience, though STL header paths may turn out strange (clangd may pick some deeply nested include instead of, say `<cstdint>`; the result may be correct and perhaps even more efficient than including the well-known headers but it's generally not what I want)
For includes pertaining to my own code, I haven't noticed any issues

**Comment by nbfalcon** [comment]
This is also a pain with `Qt`, where `#include <QPushButton>` becomes `#include <qpushbutton.h>`.

**Comment by danielmartin** [comment]
It usually works fine for me, except in a few small cases. But if many people are confused, we could enable it by default. Should we make it a Lisp `defcustom`? That way people could change the behavior more easily.

I think Google plans to improve this feature in the future, so we may want to revisit our decision later on.

**Comment by ville-h** [comment]
Automatic header inclusion results vary when programming in c and using clangd as well. Writing 'NULL' results in '#include <cstddef>' inserted when 'stddef.h' or similar would be the correct file. I don't know if this is an lsp-mode issue or a clangd issue.

**Comment by yyoncho** [comment]
What is the status of this - we are considering adding "--header-insertion=never" to default params?
