### ISSUE TITLE
Unavailable glyphs in headerline

### ISSUE THREAD

**Issue by floli** [emacs-lsp/lsp-mode#2504]
Hello,

since recently, lsp-mode displays a headerline, containing the file's path and function where point is. However, the separator uses glyphs which are not available with my font.

I have seen https://github.com/emacs-lsp/lsp-mode/pull/2500 and this commit is contained in my version of lsp.

- Emacs 27.1
- lsp-mode-20210107.22 (from elpa)

`describe-face` gives me `Family: DejaVu Sans Mono`

Thanks!

**Comment by ericdallo** [comment]
#2500 should have fixed this issue 🤔 
Although you can customize the separator with:
```elisp
(setq lsp-headerline-arrow "=>")
```

**Comment by floli** [comment]
I think the culprit here is that `(require 'all-the-icons nil t)` returns `all-the-icons`, i.e. `t` on my system. Still,
```
(all-the-icons-material "chevron_right"
                                     :face 'lsp-headerline-breadcrumb-separator-face)
```
returns
```
#("" 0 1 (rear-nonsticky t display (raise -0.24) font-lock-face (:family "Material Icons" :height 1.2 :inherit lsp-headerline-breadcrumb-separator-face) face (:family "Material Icons" :height 1.2 :inherit lsp-headerline-breadcrumb-separator-face)))
```
with the glyph at the very beginning, before zero is displayed as a placeholder.

**Comment by ericdallo** [comment]
Hum, you mean your font doesn't know how to render that all-the-icons icon?

**Comment by yyoncho** [comment]
@floli I guess you have all the icons but you haven't actually installed all the icons fonts? Have executed `M-x all-the-icons-install-fonts` ?

**Comment by floli** [comment]
Ok, after `all-the-icons-install-fonts` it works. Best thanks!

For me, issue can be closed. Maybe there is another check to see if glyphs are really available.

**Comment by surajsharma** [comment]
even after `all-the-icons-install-fonts` it isnt displaying the icons 
<img width="275" alt="Screenshot 2023-03-27 at 11 20 22 AM" src="https://user-images.githubusercontent.com/5298624/227852117-f9ff594c-b8cb-45b5-a452-b4769c1c5b59.png">

**Comment by gdonald** [comment]
> even after `all-the-icons-install-fonts` it isnt displaying the icons <img alt="Screenshot 2023-03-27 at 11 20 22 AM" width="275" src="https://user-images.githubusercontent.com/5298624/227852117-f9ff594c-b8cb-45b5-a452-b4769c1c5b59.png">

Same here.

**Comment by gdonald** [comment]
My breadcrumb thingy is missing some characters.  It seem like something is wrong with the font itself:

<img width="1920" alt="Screenshot 2023-04-11 at 4 30 56 PM" src="https://user-images.githubusercontent.com/42317655/231292921-1d8d6551-d3e3-4d4d-adc4-ccb05d949eb0.png">

Or should it render something else since I'm running console emacs in iTerm?

**Comment by kjmph** [comment]
I'm getting `` instead of chevron right.. It should look like arrow forward if the glyph carries through to your computer. As far as I can tell, when running in a terminal, we have misalignment with all-the-icon's material glyphs. However, if we switch from defaulting to the `material` `chevron_right` glyph, and instead choose to use the `faicons``angle-right` glyph, then emacs in windowed mode works, and emacs in terminal mode works. (meaning the glyph renders just fine)

In addition, when setting `lsp-headerline-arrow`, the theme colors aren't honored for some reason, so by switching the glyphs to `faicons`, the theme colors are upheld.

**Comment by kjmph** [comment]
Figured it out. I have Nerd Fonts installed at the terminal level. lsp-mode specifically uses all-the-icons. I can use chevron_right from nerd-icons.. yet, it takes quite a bit of hacking on lsp-headerline.el.

**Comment by brc** [comment]
This took a very long time to track down (even to find this issue), and the only reason I resolved it is because @kjmph posted the answer here.

No Google search finds this issue's URL when searching for "unicode e5cc" possibly because `0xE5CC` (Unicode point 58828) isn't written out in ASCII (@kjmph you rendered it all fancy-like in your comment :-P). I installed the https://github.com/mohkale/all-the-icons-nerd-fonts Emacs package and now it works with all my NF configs. Thank you @kjmph 😎

**Comment by kjmph** [comment]
Glad that helped! Similarly, it took me a while to find this. It would be fabulous if we could fix it. I don't follow what next steps are, my env continues to function with the customizations. I understand it would be a low priority to fix, yet it is one of those issues that constantly reminds the operator when they look at it.

**Comment by visigoth** [comment]
this is still very much an issue when glyph rendering is forced in a different font, such as terminals. in terminal frames, the font is controlled by the terminal emulator. for example, i use Kitty with "VictorMono Nerd Font Mono". `lsp-icons-all-the-icons-icon` uses `all-the-icons` to get a unicode code point for the glyph within the requested font (in my case, i found the bug within the rendering of the headerline breadcrumb). in `lsp-headerline--arrow-icon`, `lsp-icons-all-the-icons-icon` is asked to look up the code point for `chevron_right` in the `material` icon font. thus, the incorrect glyph shows up for the user when (1) the material icons font is installed and (2) the user is using a terminal frame.

it's not bad for the user to have the material icons font installed, nor is it wrong to use a terminal frame.

for others reading this issue: if you use terminal emacs and your terminal emulator uses a nerd-fonts font, use the `all-the-icons-nerd-fonts` MELPA package (https://github.com/mohkale/all-the-icons-nerd-fonts). but, you will need to apply the patch in https://github.com/mohkale/all-the-icons-nerd-fonts/pull/3 to get it to work with more recent all-the-icons releases.

i still think lsp-mode maintainers should consider refactoring lsp-icons to more easily allow for alternative icon resolution, such as a well documented variable or documentation about advice that should be installed.

**Comment by mciocchi** [comment]
FYI:

`M-x all-the-icons-install-fonts` did not work because of caching. You have to restart emacs afterward.

As always- you will not see the headerline until your lsp is initialized, it might take a minute.
