### ISSUE TITLE
Symbol’s function definition is void: -compose

### ISSUE THREAD

**Issue by stskyblade** [emacs-lsp/lsp-mode#2615]
**Describe the bug**
I'm using Spacemacs. I add lsp layer and add `(lsp)` to user-config. This line causes error: `Symbol’s function definition is void: -compose`. I find that there is a function called `-compose` in [this line](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L7967) . I can't find out where is its definition. Do I need to install some dependency?

**Comment by yyoncho** [comment]
You have to upgrade your `dash` package (and sync spacemacs as well).

**Comment by stskyblade** [comment]
I have update dash to dash-20210210.1449, but this error still exists. I think dash is not loaded correctly. Where should I check next? @yyoncho

**Comment by nbfalcon** [comment]
@yyoncho I see that `-compose` is part of `dash-functional.el`. Or is the latter file part of the regular dash package?

**Comment by yyoncho** [comment]
> I have update dash to dash-20210210.1449, but this error still exists. I think dash is not loaded correctly. Where should I check next? @yyoncho

did you update your spacemacs?

**Comment by yyoncho** [comment]
> @yyoncho I see that `-compose` is part of `dash-functional.el`. Or is the latter file part of the regular dash package?

yes.

**Comment by stskyblade** [comment]
Do you mean restart Emacs or git clone develop branch of Spacemacs(I haven't done this)?

**Comment by nbfalcon** [comment]
@stskyblade are you on master? Try evaluating `(require 'dash-functional)`.

**Comment by stskyblade** [comment]
I'm on develop branch and didn't update it for a long time.

**Comment by nbfalcon** [comment]
Try updating all packages using `SPC feU`.

**Comment by nbfalcon** [comment]
Afaik, spacemacs doesn't pin packages like doom, so updating it shouldn't make a difference.

**Comment by stskyblade** [comment]
I pulled develop branch and this error disappears. Thank you for your help!

**Comment by MaSven** [comment]
I have the same problem in vanilla emacs. Requiring dash in my init.el does not solve the problem

**Comment by yyoncho** [comment]
@MaSven you have to upgrade to the latest version of `dash`.

**Comment by MaSven** [comment]
Already did a package-refresh. I think i have to wait till melpa or elpa catches up

**Comment by nbfalcon** [comment]
@MaSven you could install `dash-functional` manually as a workaround for now.

**Comment by nbfalcon** [comment]
I.e. `M-x package-install RET dash-functional RET`.

**Comment by yyoncho** [comment]
> Already did a package-refresh. I think i have to wait till melpa or elpa catches up

AFAICS melpa is fine - https://github.com/magnars/dash.el/blob/0e975782086020aa12863fdb658d6a3cc748a10c/dash.el . How did you upgrade your dash version?

**Comment by nbfalcon** [comment]
Its probably ELPA.

**Comment by basil-conto** [comment]
`-compose` was recently moved from the (now deprecated) package `dash-functional` to `dash 2.18.0`.

Make sure to update both packages (or delete `dash-functional` altogether if none of your other packages depend on it).

The only complications that should arise in this area are due to MELPA using datetime versions which are incompatible with canonical ELPA version strings. In this case the onus lies on users to make sure their packages are updated and consistent when necessary. Alternatively, just install dash from [GNU ELPA](https://elpa.gnu.org/packages/dash.html), which is its authoritative source.

HTH.

**Comment by jonhermansen** [comment]
I had a very similar issue on Windows.

Upgrading my packages (and also adding `dash` as an additional package) seems to have helped.

Now LSP prompts me when opening a .c file, if I want to import the project.

**Comment by nbfalcon** [comment]
@jonhermansen just press `i` once, and the project will be remembered.

**Comment by mwilck** [comment]
FTR, I had this issue on openSUSE tumbleweed (GNU emacs 27.2-6.2), and I fixed it by *uninstalling* the `dash` and `dash-functional` packages. Whatever else I did with `dash` or `dash-functional` would show the `-compose` error message.

**Comment by basil-conto** [comment]
@mwilck Which precise versions of `dash` and `dash-functional` get installed?  The `void-function` error is almost certainly a local configuration issue.  Have you tried installing `dash` from [GNU ELPA](https://elpa.gnu.org/packages/dash.html) or [GNU-devel ELPA](https://elpa.gnu.org/devel/dash.html), or reinstalling all of your packages?

**Comment by mwilck** [comment]
I'm sorry, I was misguided. The current versions are `dash` 20210826.1449 and `dash-functional` 20210210.1449  from MELPA. I'm unsure how I arrived at this state, but this is how it is now, and the error is gone. I guess the bottom line is that I had some old version(s) of either package installed which didn't work well with `lsp-mode` (20211103.1331). Perhaps 
`lsp`'s dependencies are broken? It requires just `dash-2.18.0`.

**Comment by yyoncho** [comment]
> . Perhaps `lsp`'s dependencies are broken? It requires just `dash-2.18.0`.

The melpa versions are broken, and it doesn't matter what version we require since the melpa version will be always bigger.

**Comment by mwilck** [comment]
So what's the recommended way to pull in the correct version of `dash`? I don't find anything in the lsp installation instructions.

**Comment by yyoncho** [comment]
@mwilck here it is a guide https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/#updating-packageel-packages (except that step 1 should be: "Delete all lsp-mode packages and also the packages that can be updated.".

The best way to install emacs package is(not only lsp-mode but in general): 

a) Delete all packages that have to be updated
b) Restart emacs and install the deleted packages
c) Install the packages you want.

This is what spacemacs does.

**Comment by mwilck** [comment]
Thanks. That leaves some headroom for improvement in terms of usability I suppose :grin:

**Comment by yyoncho** [comment]
> Thanks. That leaves some headroom for improvement in terms of usability I suppose grin

I hope to see these improvements in package.el at some point.

**Comment by basil-conto** [comment]
> So what's the recommended way to pull in the correct version of `dash`?

If you don't mind manual configuration, one way is to customise `package-archive-priorities` and/or `package-pinned-packages` to ensure `dash` is installed from GNU[-devel] ELPA which uses `version-to-list`-compatible versioning.

**Comment by mwilck** [comment]
Hm, I could swear I'd tried these versions and saw the `-compose` problem. I now downgraded to them, and it seems to work. Perhaps something else was inconsistent beforehand. 

Sorry for bothering.

**Comment by jmidgren** [comment]
I had a similar problem but seemed unable to solve it without manually upgrading dash, i.e. replace version 2.17 with 2.19 with the package manager inside Emacs. I tried e.g. to only use Melpa Stable, delete all my packages and make Emacs install everything when restarting, but 2.17 would always be installed.

It turned out I had the (Ubuntu) package "elpa-dash" installed, and it happened to be version 2.17. It showed in the Emacs package manager as "external" (vs. "melpa-stable" for available packages). Thus, the solution in my case was to run
`sudo apt remove elpa-*` to ensure I have full control of the packages I use and explicitly install dash using use-package.

**Comment by jmidgren** [comment]
> Thanks for sharing this workaround.
> 
> I wonder, though, if customising `package-directory-list` (in addition to or instead of the aforementioned `package-archive-priorities` and `package-pinned-packages`) would have helped Emacs avoid such clashes to begin with.

Yes, that is probably true and I could possibly also had pinned affected packages to avoid the problem. 

I just added this comment so that others affected by the problem, from the same cause as I, would find the root of the problem. I forgot that I had elpa packages installed through apt and was not aware of how Emacs deals with those compared to sources listed in the "configuration". Generally I assume it's best to install packages from the same source where dependencies between them have been tested to some degree, versus mixing sources and risk getting widely different ages of packages.

I have been an (vanilla) Emacs user for a long time, but only recently getting into really customizing it. A rewarding and fun, yet a bit bumpy, ride so far :-)
