### ISSUE TITLE
Symbol’s function definition is void: -compose

### ISSUE THREAD

**Issue by pratik-abhyankar** [emacs-lsp/lsp-mode#2622]
I am using GNU Emacs 27.1 (latest stable) on MacOS Catalina 10.15.7 and see this error when running `lsp` or `lsp-doctor` in Emacs. LSP fails to start and thus I am not able to use it on any language modes. I see that `-compose` is referenced in the `lsp-mode.el` file but could not find its definition. 

I searched through the issues section and found out that there was a similar question asked for Spacemacs [here](https://github.com/emacs-lsp/lsp-mode/issues/2615) and was resolved by updating `dash`, something I believe is specific to Spacemacs. I am on GNU Emacs and is there a dependency I might be missing? I have  installed (using use-package) `lsp-mode`, `lsp-ui`, `lsp-ivy`, `lsp-treemacs`, `company`, `ivy`. 

If anyone wants to take a look at my init.el, you can find it [here](https://github.com/pratik-abhyankar/dot-emacs-dot-d/blob/master/init.el#L333)

**Comment by yyoncho** [comment]
The solution is the same - upgrade `dash`.

**Comment by pratik-abhyankar** [comment]
Cool.  Thanks @yyoncho. That solved the problem. For anyone else wondering how to do this and if you are using use-package to install packages, I did it this way:
```
(use-package dash
    :ensure t)
````

In case you still get the same error, refresh your package list and list with `M-x list-packages`. Search for `dash` on MELPA instead of ELPA and install it. Possible reason of error still re-surfacing could be ELPA serving `2.17` version of `dash` (at the time of writing this) whereas MELPA would get you `2.18`.

**Comment by yyoncho** [comment]
Thank you for the information - I will ping dash maintainers

**Comment by basil-conto** [comment]
`-compose` was recently moved from the (now deprecated) package `dash-functional` to `dash 2.18.0`.

Make sure to update both packages (or delete `dash-functional` altogether if none of your other packages depend on it).

The only complications that should arise in this area are due to MELPA using datetime versions which are incompatible with canonical ELPA version strings.  In this case the onus lies on users to make sure their packages are updated and consistent when necessary.  Alternatively, just install `dash` from GNU ELPA, which is its authoritative source.

HTH.
