### ISSUE TITLE
Workspace configuration response may not use file-local variables

### ISSUE THREAD

**Issue by blahgeek** [emacs-lsp/lsp-mode#2806]
## Description

Under some conditions, when `find-file` is not called interactively, `lsp-mode` will not use file-local variables while responding to workspace configuration, because the `current-buffer` haven't switched to the newly opened buffer yet.

---

## Possible fix

The following patch would fix this issue, but I'm not sure if it's OK so I didn't submit a PR

```diff
--- a/lsp-mode.el
+++ b/lsp-mode.el
@@ -5978,8 +5978,9 @@ WORKSPACE is the active workspace."
                                                     (error-message-string err))
                                         :json-false))))
                      ((equal method "workspace/configuration")
-                      (with-lsp-workspace workspace
-                        (lsp--build-workspace-configuration-response params)))
+                      (lsp-with-current-buffer (car buffers)
+                        (with-lsp-workspace workspace
+                          (lsp--build-workspace-configuration-response params))))
                      ((equal method "workspace/workspaceFolders")
                       (let ((folders (or (-> workspace
                                              (lsp--workspace-client)
```

---

## How to reproduce

(I encountered this issue while opening files using [libvterm message parsing](https://github.com/akermu/emacs-libvterm#message-passing). Here I provide a non-realistic but simpler way to reproduce.)

(Personally I use pyright to reproduce. But it should be the same for others.)

1. Install `lsp-pyright`. Add `lsp` to `prog-mode` hook. Enable `lsp-log-io`.
2. In `/tmp/py/.dir-locals.el` : `((python-mode . ((lsp-pyright-extra-paths . ["/some/extra/path"]))))`
3. In scratch buffer, run: `(run-with-timer 1 nil #'find-file "/tmp/py/hello.py")`

Expected behavior:

"/some/extra/path" should be sent in workspace configuration

Current behavioor:

"/some/extra/path" is not sent in workspace configuration

**Comment by yyoncho** [comment]
It is not guaranteed to have buffers when this core runs, so this solution won't work. 

What we can do is: do what you do when we have buffers. When we don't we can do what we do in `lsp--get-ignored-regexes-for-workspace-root`. The drawback of using an approach similar to what `lsp--get-ignored-regexes-for-workspace-root` is doing is that we won't load major-mode specific variables. But still, we should ask the users to avoid using major-mode specific dir locals because some servers support multiple major modes. 

Eventually, we can keep only the code that you have in this PR but guarded with something like `(or (car buffers) (current-buffer)`.
