### ISSUE TITLE
lsp-mode should restart server if server crashes

### ISSUE THREAD

**Issue by phst** [emacs-lsp/lsp-mode#285]
If a language server crashes, `lsp-mode` should automatically restart it once it's needed again.

This requires https://github.com/emacs-lsp/lsp-mode/issues/24 (i.e. functionality to restart in the first place).

**Comment by myrgy** [comment]
hi, with new restart function I got this error:
```
Debugger entered--Lisp error: (void-function nil)
  nil()
  lsp-restart-workspace()
  funcall-interactively(lsp-restart-workspace)
  call-interactively(lsp-restart-workspace record nil)
  command-execute(lsp-restart-workspace record)
  helm-M-x(nil #("lsp-restart-workspace" 0 21 (match-part "lsp-restart-workspace")))
  funcall-interactively(helm-M-x nil #("lsp-restart-workspace" 0 21 (match-part "lsp-restart-workspace")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

**Comment by Fuco1** [comment]
I also have a problem which is stlightly related.  I killed the lsp process buffer and the server processes because it was killing my system with some memory leak but lsp-mode still holds a reference to the dead process somewhere.  I can't call `lsp-restart-workspace` because I get `(error "Selecting deleted buffer")`.
