### ISSUE TITLE
lsp-completion-no-cache not honored

### ISSUE THREAD

**Issue by oscarfv** [emacs-lsp/lsp-mode#2944]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).
Alternatively, it will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/) which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.

### Bug description

Tracing a memory leak that occurred while using `lsp-emacs` (with Flutter projects), after Emacs reached 2.4 GB I dumped the process image and found 300000+ instances of the string `_emacsStartPoint`, which brought me to `lsp-completion.el`.

As an experiment, on a new Emacs session assigned `t` to `lsp-completion-no-cache`. After working with a Flutter project for a while, the memory leak manifested itself again. Contrary to my expectations, `lsp-completion--cache` contained data. Inspecting the source code I see some assignments to that variable not guarded by a check of `lsp-completion-no-cache`.

### Steps to reproduce

Set `lsp-completion-no-cache` to `t` and do work for a while.

### Expected behavior

`lsp-completion--cache` remains empty.

### Which Language Server did you use?

Dart/Flutter.

### OS

Linux

**Comment by ericdallo** [comment]
@kiennq

**Comment by kiennq** [comment]
The `lsp-completion-no-cache` here means not caching the returned completions from the server per keystroke. I.e,: we sent a new completion request on every user key typed.
The `lsp-completion--cache` is used even in that case since on one keystroke, we may have multiple calling to `completion-at-point` function, also we used that as global var to pass value around to processing in one keystroke too.
That's why the `lsp-completion--cache` may contain value even if `lsp-completion-no-cache` is set.

@yyoncho Do we have a method to force release memory immediately (not waiting for garbage collection) after the memory is no longer use by us?

**Comment by oscarfv** [comment]
@kiennq : the docstring of `lsp-completion-no-cache` is currently too terse, then.

As for your question, you can explicitly call `garbage-collect` anytime, but I don't think that that is what you want, nor it would make much sense. Simply stop referencing data and the garbage collector will recycle that memory, eventually.

Frankly, I'm not yet sure that the memory leak I observe is caused by `lsp-completion.el`, but I doubt that those 300000+ instances of `_emacsStartPoint` on the dumped process image are to be expected.

For the record, right now my Emacs session uses 1455 MB of RSS memory as reported by `htop`.

`garbage-collect` returns this:

```
((conses 16 4340539 1478292) (symbols 48 82647 1748) (strings 32 6895584 225736) (string-bytes 1 101887415) (vectors 16 4339848) (vector-slots 8 59199130 2108231) (floats 8 6304 3883) (intervals 56 146611 26149) (buffers 992 143))
```

And `memory-report`:

```
Estimated Emacs Memory Usage

 903.5 MiB  Overall Object Memory Usage
  47.0 MiB  Reserved (But Unused) Object Memory
  20.3 MiB  Total Buffer Memory Usage
  15.8 MiB  Memory Used By Global Variables
  10.4 MiB  Memory Used By Symbol Plists
   0.0 KiB  Total Image Cache Size

Object Storage

 517.9 MiB  Vectors
 307.6 MiB  Strings
  66.2 MiB  Conses
   7.8 MiB  Intervals
   3.8 MiB  Symbols
 138.5 KiB  Buffer-Objects
  49.2 KiB  Floats

Largest Buffers

   4.3 MiB  *info*
<truncated>
```
`lsp-completion--cache` is `nil` because I previously evaluated `lsp-completion--clear-cache`. I don't recall seeing significant differences on the output of `memory-info` after calling that function and invoking `garbage-collect`. Are there other variables where `lsp-completion` could be referencing large amounts of data?

**Comment by kiennq** [comment]
The `_emacsStartPoint` just stores a number (or a reference at most) so I don't think even with 300000+ instances it will contribute much memory (around 1MB~2MB at most?) to the whole Emacs process.
The other thing that comes with `_emacsStartPoint` is the completion data, string, which is much larger than `_emacsStartPoint`. The value stored in `lsp-completion--cache` is just a reference so it has good/bad side that it requires less memory but can keep the object in memory much longer, since the garbage collector may not be able to collect them right away.
Can you check that even with the `lsp-completion--cache` set to `nil`, run `(garbage-collect)` and dump the memory, the `_emacsStartPoint` will not reside in memory anymore?
I would like to have a more finely control garbage collector behavior like c++ smart pointer/rust, to release memory right away, else waiting for `garbage-collect` may be too late.

On another note, dart language server is known for returns huge data on completion, so after typing for a while, the problem may happen too https://github.com/dart-lang/sdk/issues/40026#issuecomment-643730264.
@ericdallo What's your experience when using dart language server, do you have any tip on reduce Emacs memory while using that?

**Comment by yyoncho** [comment]
> @yyoncho Do we have a method to force release memory immediately (not waiting for garbage collection) after the memory is no longer use by us?

There is no such method. I think that it will be useful in certain cases. 

@oscarfv I dont think running dart with no cache is good idea, it will cause tens of mbs to be generated on each keypress. What is your gc-cons-threshold? Are you using gchm?

**Comment by oscarfv** [comment]
@yyoncho Trying to disable the cache was an experiment to see if it memory leak was caused by it, by it seems that it is not possible to effectively disable the cache (unless I modify the code of `lsp-completions.el`).

On one session `gc-cons-threshold` was 100,000,000, on another 10,000,000. Same effect.

The real issue with this memory leak is not the memory growth itself (at least in my particular case), it's the increasing time that the garbage collector takes as objects accumulate.

@kiennq Rather than the space used by all those copies of `_emacsStartPoint`, it's the fact that they exist at all and the possibility of being associated to other data what caught my attention. At 300,000 instances, they were accumulating at a rate of dozens per every second that editions were made on the Flutter project.

> Can you check that even with the lsp-completion--cache set to nil, run (garbage-collect) and dump the memory, the _emacsStartPoint will not reside in memory anymore?

That would not prove anything, because the garbage collector does not zero-initialize the memory that it recovers. The data will be there until something else overwrites it.

> I would like to have a more finely control garbage collector behavior like c++ smart pointer/rust, to release memory right away, else waiting for garbage-collect may be too late.

The only difference among explicitly marking an object as unused and removing the references to it and let the garbage collector do its job is that this will happen at some future time. In any case it will cause monotonically-growing memory usage. Just stop referencing the unneeded data and the memory it uses will be recycled.

That is, unless the usage pattern of `lsp-completions` is hitting some pathological scenario of Emacs' garbage collector, but doesn't seem a probable case at this point. Most likely data is being stored and references to it are never or rarely removed.

For instance, I see `propertize` being used: are those text properties associated to the buffer that contains the source code being edited? Are they ever removed?

**Comment by yyoncho** [comment]
> The real issue with this memory leak

Which memory leak?

**Comment by oscarfv** [comment]
@yyoncho : the one that I mention on my bug report. See the part about gradually using more memory until reaching 2.4GB while editing a Flutter project and I deciding that it was enough (the performance became abysmal).

**Comment by ericdallo** [comment]
I already used multiple lsp-dart process at the same time and never noticed this kind of memory leak, even with no-cache set @kiennq

**Comment by oscarfv** [comment]
@ericdallo : how often do you restart your Emacs session? do you watch for memory usage?

I'm using Emacs 28 + native-comp, BTW.

**Comment by ericdallo** [comment]
I'm using emacs 28 + native-comp as well and I use emacsclient and don't restart it regularly, but I didn't pay that attention on memory or at least it didn't hurt me that much

**Comment by 0x28** [comment]
I think that I have the same problem as @oscarfv, but I'm using rust-analyzer instead of the Flutter language server. When I start emacs using 
```
emacs -q -l lsp-start-plain.el
```
and use lsp completion by invoking `complete-symbol` (`C-M-i`), the memory usage of the emacs process increases by ~2 MB each time. After some time, emacs becomes sluggish because `garbage-collect` takes a long time.

Are there any variables that I can inspect, which might cause this memory increase? `lsp-completion--cache` seems to be `nil` for me.

I'm also using emacs 28 + native-comp.

**Comment by kiennq** [comment]
@0x28 The `lsp-start-plain` doesn't set the `gc-cons-threshold` recommended by `lsp-mode`.
Can you try to set the `gc-cons-threshold` to see if it's improved for you?
https://emacs-lsp.github.io/lsp-mode/page/performance/

Note that setting `gc-cons-threshold` to a very big value can cause sluggish too, since the `garbage-collect` will take a long time, however, setting that to the default value (8K) will make the garbage collector runs too frequently, causing the same problem. We need to find a sweet point value in between

**Comment by 0x28** [comment]
@kiennq I set `gc-cons-threshold` to the recommended value of `100000000` in my normal config anyway. But you are correct, emacs definitely feels snappier with the `lsp-start-plain` configuration and the correct `gc-cons-threshold`.

I looked into the problem in my configuration in more detail, and it seems that `undo-tree` calls `garbage-collect` explicitly. As I understand it, an explicit call to `garbage-collect` forces garbage collection independently of `gc-cons-threshold` and `gc-cons-percentage`.

I'm not sure why `undo-tree` does this, but this call of `garbage-collect` combined with the memory usage of `lsp-mode` seems to cause the slowness I experience. I'm unsure if my problem is a `lsp-mode` bug or an `undo-tree` bug.

**Comment by oscarfv** [comment]
@0x28 @kiennq : You are discussing two different topics. How often gc is executed and how long is the time it requires is an usability issue. Emacs having a memory leak is a plain bug (a few days ago one of my long-lived seasons reached 10+ GB!). Obviously, if Emacs allocates an increasing number of objects, gc will take longer and longer, but tweaking `gc-cons-threshold` is no solution for the memory leak.

BTW, I don't use `undo-tree`.

**Comment by oscarfv** [comment]
Since the real problem is the memory leak, I'll close this bug report and open a new one once I have some clue about the cause.

**Comment by blahgeek** [comment]
@oscarfv  I have the exact same problem as you: memory leak to >1GB and the long pause of GC is making me crazy.

Some investigation leads me to `response-handlers` in `lsp-clients`, which seems to be leaking. While I'm still investigating this, can you check it in your long-running emacs session? You can run this to see the number of kept response handlers:

```
(hash-table-size (lsp--client-response-handlers (gethash 'clangd lsp-clients)))
```

(replace `clangd` with your lsp id).

**Comment by oscarfv** [comment]
Sorry for the long delay. Until recently I had no opportunity to work on a project that makes use of emacs-lsp.

It seems that the problem had disappeared.  After a few sessions of several hours each with lsp-dart the memory used by Emacs stabilizes within the 500-600 MB range. Currently I'm using `lsp-dart` 20220120.202 and `lsp-mode` 20220115.1742.

P.D.: now I see the mention to #3062. Probably it was that what fixed the problem for me. Thanks @blahgeek and @yyoncho.
