### ISSUE TITLE
lsp-sourcekit ;; completion stops working after lsp server returns an error

### ISSUE THREAD

**Issue by wibed** [emacs-lsp/lsp-mode#3028]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

completion stopped working after receiving a completion error from the sourcekit-lsp

the completion stops working if one follows the reproduction right here:
```
func hello(na
------------^
```
and the following logs are produced. the communication with the sourcekit-lsp 
continues, as the stacktrace shows, but completion stops working.

### Steps to reproduce

1. open swift file
2. set the root path for the project
3. type "fun", select the proper ("func") selection from the dropdown
4. try typing out " hello(name: String)" after that

### Expected behavior

the completion to work after receiving a completion error from the sourcekit-lsp

# current behavior
completion stopped working after receiving a completion error from the sourcekit-lsp

### Which Language Server did you use?

# context
os: linux 5.12.19_1
emacs: 28.0.50 (x86_64)
language: swift (swift-mode)
lsp: lsp-mode, lsp-sourcekit

### OS

Linux

### Error callstack

```emacs-lisp
- [company-diag](https://termbin.com/2oj0)
- [backtrace](https://termbin.com/so0c)
- [lsp-log](https://termbin.com/rzgk)
- [sourcekit-ls](https://termbin.com/s5ss)
- [stacktrace](https://termbin.com/1rqs)
```

### Anything else?

- ~~trying to clean the company cache manually had no effect~~
- adding (setq yas-inhibit-overlay-modification-protection t) had no effect

UPDATE:
- manually cleaning the cache with `(lsp-completion--clear-cache t)` had some effect, manual completion at point works. but even restarting `swift-mode` does not bring back expected functionality.
- disabling cache at startup setting `(setq lsp-completion-no-cache t)` had no effect.

**Comment by wibed** [comment]
@danielmartin i am fairly new to emacs. as far as i can tell `sourcekit-lsp` only establishes the connection to the lsp server

**Comment by wibed** [comment]
@yyoncho reading into https://github.com/emacs-lsp/lsp-mode/issues/1853 and https://github.com/emacs-lsp/lsp-mode/pull/1896

i found
```el
(defun lsp-completion--clear-cache (&optional keep-last-result)
  "Clear completion caches.
KEEP-LAST-RESULT if specified."
  (-some-> lsp-completion--cache
    (cddr)
    (plist-get :markers)
    (cl-second)
    (set-marker nil))
  (setq lsp-completion--cache nil)
  (unless keep-last-result (setq lsp-completion--last-result nil)))
```

clearing the cache i got company to complete at point (company-complete) but it didnt fire automatically
is there a workaround, to keep company functionality?

**Comment by kiennq** [comment]
@wibed Can you try to set `lsp-completion-no-cache` to `t` and retry?

**Comment by wibed** [comment]
@kiennq the error persists. resulting from the -32800, crashing completion.

**Comment by kiennq** [comment]
@wibed after the error is showing up, if you try to type more, is a new completion coming?

**Comment by wibed** [comment]
nope completion stops working after the error
- [backtrace](https://termbin.com/so0c)

**Comment by wibed** [comment]
i am new to emacs and have not had the chance to get in touch with lisp. ill link to vscode client to sourcekit-lsp, which works fine

https://github.com/apple/sourcekit-lsp/tree/main/Editors/vscode

**Comment by wibed** [comment]
@kiennq as linked above the problem is better explained in said words
```
The problem seems to be with lsp-completion--get-context that is used as a parameter to the completion request. 
For whatever reason, lsp-completion--cache gets set with an incomplete marker. 
The context sets specific :trigger-kind in this case which seems to break the completions.

Unfortunately, just deactivating caching with (setq lsp-completion-no-cache 't) doesn't seem to be enough, 
the :incomplete marker is still set.
```

**Comment by wibed** [comment]
this one seems related

https://github.com/emacs-lsp/lsp-mode/issues/2970

**Comment by kiennq** [comment]
I think the problem here is that the server returns an error and it translated to Emacs user error, which will throw off the cache clearing part of lsp-mode's completion.
I will push a PR for this soon

**Comment by wibed** [comment]
@kiennq 

> I think the problem here is that the server returns an error and it translated to Emacs user error, which will throw off the cache clearing part of lsp-mode's completion.
> I will push a PR for this soon

id say the completion message to the server is malformed triggering an error from the server blocking the completion from further actions. the lsp error states, that it received unexpected string as completion request.

```
2021-09-19 05:52:44.639 sourcekit-lsp[48:5e34c700] triggerFromIncompleteCompletions with incompatible completion session; expected DocumentURI(storage: file:///work/test/swift/Package.swift)@153, but got DocumentURI(storage: file:///work/test/swift/Package.swift)@157
```
i recreated it for the log links above are dead

**Comment by BrandonShega** [comment]
> I think the problem here is that the server returns an error and it translated to Emacs user error, which will throw off the cache clearing part of lsp-mode's completion.
> I will push a PR for this soon

Any progress on this or can I help out with it? I'm also running into this while trying to do iOS development with Emacs.

**Comment by kiennq** [comment]
@wibed @BrandonShega Can you upload the lsp-trace log again? It got expired.
My initial thought about this problem is because the user error inside `lsp-request-while-no-input`, but it turns out the problem is elsewhere.

> id say the completion message to the server is malformed triggering an error from the server blocking the completion from further actions. the lsp error states, that it received unexpected reference as completion request.
> 
> ```
> 2021-09-19 05:52:44.639 sourcekit-lsp[48:5e34c700] triggerFromIncompleteCompletions with incompatible completion session; expected DocumentURI(storage: file:///work/test/swift/Package.swift)@153, but got DocumentURI(storage: file:///work/test/swift/Package.swift)@157
> ```
> 
> i recreated it for the log links above are dead

Sending completion requests with trigger kind as incomplete is normal (as specified in LSP spec).
However, the server is complaining the Document id is not matched? @yyoncho, do you have any information on that?

@wibed, @BrandonShega Can provide a new log when the issue happens?

**Comment by BrandonShega** [comment]
@kiennq I'm not sure what the trace log is, sorry.  I've used Emacs in the past but not much with LSP.  I do have a bunch of errors in the `*sourcekit-ls::stderr` buffer: https://pastebin.com/DYcz0Afv

**Comment by wibed** [comment]
here we go:
[backtrace](https://termbin.com/kb1x0)
[stacktrace](https://termbin.com/ujud)
[sourcekit error](https://termbin.com/u1g1)

**Comment by wibed** [comment]
any progress on this? or can i help out in other ways?

**Comment by konrad1977** [comment]
Anyone got a working solution, even if its just temporary?

**Comment by yyoncho** [comment]
Can someone post client-server log which includes:
1. The error
2. The behaviour after the error after `M-x company-complete` (which forces the completion call). 

It will be best if the logging is enabled just before the error.

**Comment by konrad1977** [comment]
I am completely new to Emacs (my first week), will the message-buffer be enough, or do I need to do something else? How do I add logging?

**Comment by yyoncho** [comment]
@konrad1977 use `M-x lsp-toggle-trace-io` and `M-x lsp-workspace-show-log`.

**Comment by konrad1977** [comment]
https://justpaste.it/3vbi6

I dunno if it correct?

**Comment by yyoncho** [comment]
Use M-x lsp-workspace-show-log to get the buffer with client/server log.

**Comment by konrad1977** [comment]
https://ctxt.io/2/AABgaitaFQ

The log is a bit log. But as soon the error occurred I stopped. So it's probably somewhere in the end. Good luck with the bug hunting. Just let me know if you want to try something else.

**Comment by konrad1977** [comment]
https://justpaste.it/4ez4o
I updated a new log. Saw that the previous one expired.
Any news or work arounds?

**Comment by konrad1977** [comment]
Still no solution? Let me know if I can help out somehow?

**Comment by wibed** [comment]
has noone expirienced this issue? any progress?

**Comment by clint-k** [comment]
I have the same issue.
```
Company: An error occurred in auto-begin
Company: backend company-capf error "request cancelled" with args (candidates ...)
```
` (setq lsp-completion-no-cache t)`didn't help.
I wonder why only some people are facing the problem.

**Comment by konrad1977** [comment]
@clint-k I switched to TabNine and SourceKitten with Company for code completions. I dunno why this is happening for LSP, but both LSP and DAP seems a bit broken for Swift projects/workspaces - but I heard that they work great for package based projects.

**Comment by wibed** [comment]
can this be closed?

**Comment by prittjam** [comment]
Company mode for me just randomly works and stops working. It's a productivity killer.

**Comment by wibed** [comment]
@prittjam 
i just went ahead and got a mbpro, but if you get lucky using 

> @clint-k I switched to TabNine and SourceKitten with Company for code completions. I dunno why this is happening for LSP, but both LSP and DAP seems a bit broken for Swift projects/workspaces - but I heard that they work great for package based projects.

please do tell

**Comment by wibed** [comment]
@prittjam 
https://pvzig.medium.com/swift-development-with-visual-studio-code-on-linux-99cac3918582

**Comment by crabbkw** [comment]
I have tracked this issue down to the fact that lsp-mode is sending `triggerKind: 3`  which means to continue a completion from an incomplete completion, but it is sending a different file position than what sourcekit-lsp is expecting, so sourcekit-lsp cancels the request as it is "invalid" to continue a completion from a different position in the file.

I further found that modifying lsp-completion.el's `lsp-completion--get-context` function so that in the case of incomplete completions we unilaterally state that we're triggering from user input:

Here's a patch that while terrible works for me locally:

```diff
--- lsp-completion.el	2022-11-04 18:18:17.000000000 -0500
+++ /Users/ccrabb/Desktop/lsp-completion.el	2022-11-04 18:19:05.000000000 -0500
@@ -397,21 +397,23 @@
 (defun lsp-completion--get-context (trigger-characters)
   "Get completion context with provided TRIGGER-CHARACTERS."
   (let* ((triggered-by-char non-essential)
          (trigger-char (when triggered-by-char
                          (lsp-completion--looking-back-trigger-characterp
                           trigger-characters)))
          (trigger-kind (cond
                         (trigger-char
                          lsp/completion-trigger-kind-trigger-character)
                         ((equal (cl-second lsp-completion--cache) :incomplete)
-                         lsp/completion-trigger-kind-trigger-for-incomplete-completions)
+                         ;; Begin Casey hack
+                         ;; lsp/completion-trigger-kind-trigger-for-incomplete-completions)
+                         lsp/completion-trigger-kind-invoked) ;; end Casey hack
                         (t lsp/completion-trigger-kind-invoked))))
     (apply #'lsp-make-completion-context
            (nconc
             `(:trigger-kind ,trigger-kind)
             (when trigger-char
               `(:trigger-character? ,trigger-char))))))
 
 (defun lsp-completion--sort-completions (completions)
   "Sort COMPLETIONS."
   (sort
```

The other terrible option for monkeypatching would be to redefine `lsp/completion-trigger-kind-trigger-for-incomplete-completions` to have the same value as `lsp/completion-trigger-kind-invoked`. At this time that constant is only used in this one spot so it doesn't currently have other impacts. I also tested this locally using `(defconst lsp/completion-trigger-kind-trigger-for-incomplete-completions 1)` as part of my mode hook for swift, and that fixes the completion problem.

It is likely that either of my above monkey patches will cause problems if you actually want to get further completions from an incomplete result set.

I have not dug in to figure out why we're falling into the `((equal (cl-second lsp-completion--cache) :incomplete)` branch. I suspect the code has race conditions as we're not doing anything to see if the current completion context (file name and position in file) is the same as what was cached; so if the cache is populated by a request coming in asynchronously we could have issues. The real fix would be ensuring we do not fall into this branch when manually invoking a completion or invoking an auto-completion from a trigger character.

**Comment by yyoncho** [comment]
@crabbkw to me it looks like an acceptable solution. Willing to turn it into a PR?

**Comment by yyoncho** [comment]
> I have tracked this issue down to the fact that lsp-mode is sending `triggerKind: 3` which means to continue a completion from an incomplete completion, but it is sending a different file position than what sourcekit-lsp is expecting, so sourcekit-lsp cancels the request as it is "invalid" to continue a completion from a different position in the file.

I am a bit confused. Why the server would want to have the original position here? If the server does not have the cursor position then it won't know what to filter against.

**Comment by crabbkw** [comment]
LSP is sending a request like:

```
[Trace - 01:57:56 PM] Sending request 'textDocument/completion - (90)'.
Params: {
  "textDocument": {
    "uri": "file:///home/ccrabb/src/SimpleSwift/Sources/SimpleSwift/SimpleSwift.swift"
  },
  "position": {
    "line": 13,
    "character": 40
  },
  "context": {
    "triggerKind": 3
  }
}
```

To which we get the response:
```
[Trace - 01:57:56 PM] Received response 'textDocument/completion - (90)' in 1ms.
Result: {
  "message": "request cancelled",
  "code": -32800
}
```

And stderr of sourcekit-lsp has:
```
2022-11-15 13:57:56.398 sourcekit-lsp[50371:e1997640] triggerFromIncompleteCompletions with incompatible completion session; expected DocumentURI(storage: file:///home/ccrabb/src/SimpleSwift/Sources/SimpleSwift/SimpleSwift.swift)@401, but got DocumentURI(storage: file:///home/ccrabb/src/SimpleSwift/Sources/SimpleSwift/SimpleSwift.swift)@408
```

I'm fairly certain that the 401 and 408 are byte/character offsets into the file (same for me since I'm using ascii). In my case the line it bombs on is:

`encoder.outputFormatting.insert(` -- the completion session that sourcekit-lsp is expecting is for the `insert` part, whereas the completion lsp-mode is requesting (with continuation) is for after the `(`. In this case lsp-mode should be starting a new continuation session (triggerKind 1 or triggerKind 2), not continuing an existing session. In fact, I think the only time lsp-mode should be sending `triggerKind: 3` is if you're scrolling through the list of available completions, hit the end of the local list and the server said that the list was incomplete. We should never send `triggerKind: 3` when typing new characters into the buffer. We either want `triggerKind: 1` if the user manually starts the completion, and `triggerKind: 2` if the user typed a character that is a completion trigger character.

In order for continuations to work lsp-mode would need to be able to tell the Emacs completion framework (whether it is Company or the ootb framework): "Here is a partial list of results, you can get more results by..."

This problem is reproducible on Ubuntu 22.04 using the binary distribution of swift found at https://www.swift.org/download/ . I've attached a small swift package that repros easily.


[SimpleRepro.zip](https://github.com/emacs-lsp/lsp-mode/files/10016071/SimpleRepro.zip)

**Comment by yyoncho** [comment]
Hm... I see what are the server expectations but I don't see anything in the spec that describes these expectations. As you can see here https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionTriggerKind neither 1 or 2 are a good match for "received incomplete list, user typed and then we want more". But I guess that might be an implicit contract implemented in vscode...

Willing to turn this into a PR?

**Comment by crabbkw** [comment]
From the spec:

```
	/**
	 * Completion was triggered by typing an identifier (24x7 code
	 * complete), manual invocation (e.g Ctrl+Space) or via API.
	 */
	export const Invoked: 1 = 1;

	/**
	 * Completion was triggered by a trigger character specified by
	 * the `triggerCharacters` properties of the
	 * `CompletionRegistrationOptions`.
	 */
	export const TriggerCharacter: 2 = 2;

        /**
	 * Completion was re-triggered as the current completion list is incomplete.
	 */
	export const TriggerForIncompleteCompletions: 3 = 3;
```

TriggerForIncompleteCompletions isn't for continuing to type (which may narrow down the possible completions).  TriggerForIncompleteCompletions is for when the user scrolling through the various options, hits the end of the set the server already sent, so the lsp-client requests a "continuation" of the previously started completion. This interpretation is reinforced by the `24x7 code complete` in the comment describing when `Invoked` should be used.

If the user enters any new characters into the buffer we really should be sending either `Invoked` or `TriggerCharacter`.

I'm happy to turn this into a PR, but need some guidance about what you want to do.

I think the `lsp-completion--get-context` function should only ever return `lsp/completion-trigger-kind-invoked` or `lsp/completion-trigger-kind-trigger-character`. That only fixes half of the problem. The other half of the problem is teaching Company or Emacs' ootb completion framework how to use lsp-mode to request additional completions when it gets a partial list of completions initially and then the user scrolls near the end of that list.

I can easily create a PR to fix `lsp-completion--get-context` as described above. Fixing the second half of the problem is much more involved. I worry that if there have been different assumptions about how incomplete completion responses are supposed to work then all uses of lsp-completion--cache will have to be inspected to make sure we're not violating some other assumptions when we make the change to lsp-completion--get-context.

**Comment by yyoncho** [comment]
> I can easily create a PR to fix `lsp-completion--get-context` as described above. Fixing the second half of the problem is much more involved. I worry that if there have been different assumptions about how incomplete completion responses are supposed to work then all uses of lsp-completion--cache will have to be inspected to make sure we're not violating some other assumptions when we make the change to lsp-completion--get-context.

The second part is not something that we need right now. ATM it is expected for the user to type more to get stuff filtered.

**Comment by crabbkw** [comment]
In the PR I've just opened I've fixed the problem in a slightly different way that I had originally intended. A trigger-for-incomplete-completions should occur if the completion context is the same as the previous request and the previous request was incomplete. If the context is different then we issue a new completion request. If the user just typed a trigger character then we issue a new trigger-character completion request regardless of whether the context is the same. This seemed a bit less risky than simply never issuing an `lsp/completion-trigger-kind-trigger-for-incomplete-completions`. The function that calls `lsp-completion--get-context` already calculated a `same-session?` value that is now simply passed down.
