### ISSUE TITLE
lsp-scala

### ISSUE THREAD

**Issue by rossabaker** [emacs-lsp/lsp-mode#327]
I just created an [lsp-scala](https://github.com/rossabaker/lsp-scala) project.  The Scala language server is still immature, but I'm hopeful we can get a great experience on emacs.

I'd be happy to move the project into this org if there's interest.  I'm also looking into publishing to MELPA, which is new to me.

**Comment by kat-co** [comment]
I think the most important thing you can do to ensure your module is always ready for inclusion into (m)elpa is to ensure anyone who commits is OK with assigning their copyright over to the GNU foundation. Otherwise, you'll have to track everyone who committed down to ask for consent.

This assumes you'd like to assign copyright over to the GNU foundation (not a requisite). Here's why you might want to do that: 

> GNU packages need not be FSF-copyrighted; this is up to the author(s), generally at the time the package is dubbed GNU. When copyright is assigned to the FSF, the FSF can act to stop GPL violations about the package. Otherwise, legal actions are up to the author(s). 

https://www.gnu.org/prep/maintain/maintain.html#Copyright-Papers

**Comment by kat-co** [comment]
[Here's](https://github.com/emacs-lsp/lsp-mode/issues/83#issuecomment-300731577) more discussion on that for `lsp-mode` for reference.

**Comment by vibhavp** [comment]
Added to https://github.com/emacs-lsp/lsp-mode/wiki/Languages-and-Plugins.
