### ISSUE TITLE
Support for setting cargo features via rust-analyzer.cargo.features

### ISSUE THREAD

**Issue by ia0** [emacs-lsp/lsp-mode#3375]
Hi,

I would like to change the list of features that rust-analyzer is using to compile the code (from within emacs, so without changing the default features in the `Cargo.toml`). Searching on internet, it looks like there is some `rust-analyzer.cargo.features` configuration for that. But I can't see it in lsp-mode. The closest I see is [`lsp-rust-analyzer-cargo-override-command`](https://emacs-lsp.github.io/lsp-mode/page/lsp-rust-analyzer/#lsp-rust-analyzer-cargo-override-command) but I don't know how to use it.

I didn't find any mention of this feature request in [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892).

Thanks!

**Comment by brotzeit** [comment]
It's probably a little hard to find in this case.

```elisp
    :cargo (:allFeatures ,(lsp-json-bool lsp-rust-all-features)
            :noDefaultFeatures ,(lsp-json-bool lsp-rust-no-default-features)
            :features ,lsp-rust-features
```

You are probably looking for `lsp-rust-features`.

**Comment by brotzeit** [comment]
You can use `setq` instead of `set-variable` and put it in your emacs config.

**Comment by ia0** [comment]
I mean more something like a function that permits to edit the variable to easily add or remove features and that would automatically restart rust-analyzer (or if it's possible to push the config, it's even better). But for that I'll need to learn elisp again, so it will wait this week-end.

**Comment by brotzeit** [comment]
Have fun ;)

Is your question answered ?

**Comment by ia0** [comment]
Yes thanks! :-)

**Comment by ia0** [comment]
For posterity, here is what I did to edit the features:

```
(defun edit-lsp-rust-features ()
  "Edit lsp-rust-features."
  (interactive)
  (setq lsp-rust-features
        (read-minibuffer "Features? " (format "%S" lsp-rust-features))))
```

I wasn't able to call `lsp-workspace-restart` automatically because it takes an argument and I don't know how to get it. But I've just bound both commands to a shortcut so I can just do:
- `C-c f` edit features
- `C-c w r`

Thanks again for pointing me out to `lsp-rust-features`!

**Comment by yyoncho** [comment]
@ia0 FYI there is M-x customize-variable

**Comment by ia0** [comment]
Yes I've seen this too, but it's very unconvenient to use. The cursor is not directly on the old value and Enter doesn't change the value. You need to click `Apply`. That's too many extra-steps compared to directly editing the value.

**Comment by yorodm** [comment]
Another take on @ia0 function, I find more convenient to just type `feature-a,feature-b`

```elisp
(defun edit-lsp-rust-features ()
  "Edit lsp-rust-features."
  (interactive)
  (let ((current-features (mapconcat 'identity lsp-rust-features ",")))
    (setq lsp-rust-features
          (vconcat (s-split "," (read-string "Features? " current-features))))))
```

**Comment by ia0** [comment]
Thanks @yorodm ! I was actually having issues when typing multiple features today that I had to update the prompt to remind me that the syntax is `["foo" "bar"]` and not `["foo", "bar"]`. I'll try your function next time I get the chance.

**Comment by ia0** [comment]
I modified it a bit to correctly map the empty string to the empty vector:
```
(defun edit-lsp-rust-features ()
  "Edit lsp-rust-features."
  (interactive)
  (let ((old-features (mapconcat 'identity lsp-rust-features ",")))
  (let ((new-features (read-string "Features? " old-features)))
  (setq lsp-rust-features (vconcat (split-string new-features "," t))))))
```

**Comment by ia0** [comment]
For posterity, I improved the command to support `lsp-rust-no-default-features`:

```lisp
(defun edit-lsp-rust-features ()
  "Edit lsp-rust-features and lsp-rust-no-default-features."
  (interactive)
  (let ((old-features (mapconcat 'identity lsp-rust-features ",")))
  (when lsp-rust-no-default-features
    (setq old-features (concat "=" old-features)))
  (let ((new-features (read-string "Features? " old-features)))
  (setq lsp-rust-no-default-features (string-prefix-p "=" new-features))
  (if lsp-rust-no-default-features (aset new-features 0 ?,))
  (setq lsp-rust-features (vconcat (split-string new-features "," t))))))
```

The syntax is an optional `=` (i.e. set instead of add features) followed by a comma-separated list of features:
- `foo,bar` is like `--features=foo,bar`
- `=foo,bar` is like `--no-default-features --features=foo,bar`

**Comment by ntc2** [comment]
**I'm finding that adding a feature to `lsp-rust-features` isn't enough to make `rust-analyzer` actually `cargo check` the code that is hidden behind that feature: I also need to add the feature to `lsp-rust-analyzer-checkonsave-features`!** Adding the feature in both places seems to be equivalent to adding it to the `default` features in `Cargo.toml`, but adding the feature in only one of `lsp-rust-features` or `lsp-rust-analyzer-checkonsave-features` is not enough.

Looking at the part of the code that @brotzeit [linked to earlier](https://github.com/emacs-lsp/lsp-mode/issues/3375#issuecomment-1057178315), I see that it has "features" configs in two places:
1) the `:cargo : features` config uses `lsp-rust-features`: https://github.com/emacs-lsp/lsp-mode/blob/c36b95be6625dac5a37d3874a1a738e0c84ac39f/clients/lsp-rust.el#L1683-L1685
2) the `:checkOnSave :features` config uses `lsp-rust-analyzer-checkonsave-features`: https://github.com/emacs-lsp/lsp-mode/blob/c36b95be6625dac5a37d3874a1a738e0c84ac39f/clients/lsp-rust.el#L1669-L1673

It seems that (1) `lsp-rust-features` is responsible for warnings about code being disabled, e.g. greying out of code covered by `#[cfg(feature = "<my feature>")]` with `[inactive-code]` warning, and module-level `[unlinked-file]` warnings for modules that are currently not included in the module tree, due to parent module's `use <child module>` being hidden behind `#[cfg(feature = "<my feature>")]`.

However, it seems that (2) `lsp-rust-analyzer-checkonsave-features` is necessary for rust analyzer to actually `cargo check` the disabled code (e.g. in `[unlinked-file]` files), independent of the setting of `lsp-rust-features`!

So, perhaps this issue should be reopened? I think a proper resolution would amount to an ergonomic way to get the effect of changing the `default` features, without actually editing the `Cargo.toml` file. Looking at the `rust-analyzer` docs, there seem to be two corresponding, separate settings there, i.e. [`rust-analyzer.cargo.features`](https://rust-analyzer.github.io/manual.html#rust-analyzer.cargo.features) corresponding to `lsp-rust-features` here, and [`rust-analyzer.check.features`](https://rust-analyzer.github.io/manual.html#rust-analyzer.check.features) corresponding to `lsp-rust-analyzer-checkonsave-features` here. **However**, altho those settings are minimally documented, it does say that `rust-analyzer.check.features` "Defaults to `rust-analyzer.cargo.features`", so I think at minimum a faithful analog here would be for `lsp-rust-analyzer-checkonsave-features` to effectively default to `lsp-rust-features`.

I'm going to attempt to make the "check" features default to the "cargo" features and submit a PR if I can get that working ...

**Comment by ntc2** [comment]
I just [submitted a PR](https://github.com/emacs-lsp/lsp-mode/pull/4542) fixing the bug I mentioned in [my last comment](https://github.com/emacs-lsp/lsp-mode/issues/3375#issuecomment-2324428940).

With that PR, the `edit-lsp-rust-features` function from [this comment](https://github.com/emacs-lsp/lsp-mode/issues/3375#issuecomment-1070803316) works for me. And you can make it auto-reload the rust-analyzer by adding `(call-interactively 'lsp-workspace-restart)` at the end, i.e.

```elisp
(defun edit-lsp-rust-features ()
  "Edit `lsp-rust-features' and `lsp-rust-no-default-features'.

If the first character of input is '=', then
`lsp-rust-no-default-features' is set. Multiple features are
specified by separating them with commas. The value \"all\" is
special and means \"--all-features\"."
  (interactive)
  (let ((old-features (mapconcat 'identity lsp-rust-features ",")))
    (when lsp-rust-no-default-features
      (setq old-features (concat "=" old-features)))
    (let ((new-features (read-string "Features? " old-features)))
      (setq lsp-rust-no-default-features (string-prefix-p "=" new-features))
      (if lsp-rust-no-default-features (aset new-features 0 ?,))
      (setq lsp-rust-features (vconcat (split-string new-features "," t)))))
  (call-interactively 'lsp-workspace-restart))
```
