### ISSUE TITLE
new server fired up for every buffer

### ISSUE THREAD

**Issue by valignatev** [emacs-lsp/lsp-mode#340]
I'm not sure if it belongs here or in the [lsp-python](https://github.com/emacs-lsp/lsp-python), but anyway:

New `pyls` process is being fired for each new python buffer, and it constantly warns with "can't find project root" for builtin modules. I didn't see anything specific in the lsp-python configuration, that's why I open this issue here.

My question is if this is an expected behavior and if it's not - what should we do about it? Should we somehow reuse running server process?

P.S. Please tell me If this issue belongs in another repository - I'll recreate or reference it there.

P.P.S - Thanks for the awesome work!

**Comment by IvanMalison** [comment]
I think that I've noticed this happening with lsp-haskell/hie as well. Seems like a new hie instance is started even if there is already one running for the current project.

**Comment by tskinn** [comment]
I just started checking emacs-lsp out yesterday so I could wrong but I it looks like lsp-python is searching parent directories for "setup.py" (https://github.com/emacs-lsp/lsp-python/blob/master/lsp-python.el#L20) and if it doesn't find it, emacs-lsp throws the message and assumes the directory of the file is the root of the project and starts a new server.

I imagine you just need to edit the lambda function passed to the `lsp-make-traverser` function so that it looks for the project directory in a more intelligent way.
