### ISSUE TITLE
Plans for `lsp-code-actions`?

### ISSUE THREAD

**Issue by abingham** [emacs-lsp/lsp-mode#353]
I'm starting to look into how to add more refactorings to [`python-language-server`](https://github.com/palantir/python-language-server) and access them with `lsp-mode`. From what I gather (I'm pretty new to LSP), this needs to happen through code actions. The `lsp-mode` code has some notes indicating that code actions can't be applied, and indeed I can't find any way to use them.

So I was wondering: what is the plan for using code actions? `lsp-execute-code-action` seems like it's trying to do something, but it seems that no attempt is ever made to populate `lsp-code-actions`, so it doesn't do much. 

I've got a substantial chunk of free time (a transatlantic flight) coming up where I could dig into this issue, but I could use some guidance as to how the feature is envisioned to work.

**Comment by vibhavp** [comment]
`lsp-code-actions` is populated in lsp--text-document-code-action, which in turn is called [inside `lsp--on-hover`](https://github.com/emacs-lsp/lsp-mode/blob/c8f60c692b94677a4c481ff3fea06966f72070e9/lsp-methods.el#L1506). lsp-mode still needs a better way to access code actions, IMO.

**Comment by alanz** [comment]
FYI, haskell-lsp has some refactoring commands, which are exposed using execute command.  This unfortunately needs client code for each of them.  See e.g. https://github.com/emacs-lsp/lsp-haskell/blob/master/lsp-haskell.el#L56

We also attach code actions to Diagnostics, so that we can apply fixes for hlint hints.

**Comment by yyoncho** [comment]
As a side note I am using the following function to retrieve the current actions and run them:

@vibhavp do you think it will be usefull as part of LSP mode(or maybe lsp-execute-code-action to check whether code actions are available and rertrieve them if they aren't)?

```emacs-lisp
(defun lsp-action-retrieve-and-run ()
  "Retrieve, select, and run code action."
  (interactive)
  (lsp--cur-workspace-check)
  (lsp--send-request-async (lsp--make-request
                            "textDocument/codeAction"
                            (lsp--text-document-code-action-params))
                           (lambda (actions)
                             (setq lsp-code-actions actions)
                             (condition-case nil
                                 (call-interactively 'lsp-execute-code-action)
                               (quit "Quit")))))
```

**Comment by abingham** [comment]
> lsp-code-actions is populated in lsp--text-document-code-action, which in turn is called inside lsp--on-hover.

Yeah, I saw that, but since `lsp--on-hover` didn't seem to be connected to anything I wasn't sure if that was meaningful. Is the intent to hook that to some sort of hover handler (if such a thing exists)?

**Comment by abingham** [comment]
@yyoncho This is along the lines of what I was imagining. I guess the missing complexity is properly refreshing buffers and such based on the changes.

**Comment by yyoncho** [comment]
@abingham actually it works as it is. You may try it.

**Comment by abingham** [comment]
> actually it works as it is. You may try it.

It does work (thanks!), but from what I can tell it relies on auto-revert or something on the emacs end to actually show the changes to the user. This works for some actions, but I was thinking of situations where e.g. a file is renamed; in that case we want to close the original buffer and open the new one. I guess in those cases we need custom action handlers (if I'm reading the code correctly).

So is something like your `lsp-action-retrieve-and-run` what you're thinking of for the "real" UI, or are there plans for something more sophisticated, e.g. popups or something? And in either case, how can we handle actions that require input from the user (e.g. extract-method requires a name for the new function)?

**Comment by yyoncho** [comment]
It does not rely on auto revert since the changes are applied by emacs not the server. For more sophisticated UI you might try LSP UI. Based on my understanding the more complex actions will ask the user for input and won't be "actions". Current actions are more like quick fix, no user input required. As a side note "Extract method" works for lsp java and it creates a method with default name.

**Comment by abingham** [comment]
> Based on my understanding the more complex actions will ask the user for input and won't be "actions".

How are these modeled in LSP? I'm still getting up to speed on the terminology, etc., and the LSP docs seem to put "refactoring" under "Code Action Request".

**Comment by yyoncho** [comment]
@abingham sorry for the late response, I kind of missed your question. First, I want to mention that the comments below are based only on my understanding of LSP protocol and someone with better understanding of the protocol could prove me wrong. 

There are standard LSP methods (e. g. codeActions, rename, etc) which are usually mapped by `lsp-mode`. When the LSP is not sufficient a particular language server could introduce a protocol extension. I will give you examples from `lsp-java` since I am working on it - https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L210 . Due to the fact that update project configuration requires the project file as a param it is realized as a protocol extension and it is mapped by the `lsp-java`. In a similar manner, if you have a custom refactoring which requires user input provided by the server, you could create a method on the client side (in emacs) which asks the user for the required input.
