### ISSUE TITLE
Move lsp-imenu to individual lsp clients

### ISSUE THREAD

**Issue by wyuenho** [emacs-lsp/lsp-mode#381]
RIght now lsp-imenu just naively displays the imenu index by types as they come back from the server, in many cases this is qualitatively worse than the simple regex based imenu index from a lot of modes. 

In lsp-python for example, user defined classes and imported classes are mixed together into the same group, functions, constants and variables are mixed too. Worse, the class methods are at the same levels as classes, so you don't know when method belongs to which class by looking at imenu.

In lsp-javascript-typescript, imported modules are mixed into the list of variables, and methods that belong to classes are top-level'ed too.

IMHO, imenu list presentations should be client specific and tailors to their idiosyncrasy.

**Comment by vibhavp** [comment]
`lsp-imenu` is an [incredibly thin wrapper](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-imenu.el#L45) over the `textDocument/documentSymbol` method. It simply removes the symbols which are not in the current file and creates an alist mapping every symbol type to its respective symbol list.

I haven't used any other editors/IDEs, but I expect that any symbol navigating functionality to be similar to what lsp-imenu does (perhaps with a GUI, but the browsable *content* being the same nonetheless). From what I can understand, this is a problem more to do with the language server itself, rather than lsp-mode or lsp-imenu.

Regardless, I'm interested in how lsp-mode clients packages can augment/modify imenu/`documentSymbol`, and how lsp-mode should allow that.

**Comment by vibhavp** [comment]
>  From what I can understand, this is a problem more to do with the language server itself, rather than lsp-mode or lsp-imenu.

For example, this is the output of `helm-imenu` with lsp-cquery, which only shows symbols in the current file: ![cquery imenu](https://i.imgur.com/6OANSWE.png)

**Comment by wyuenho** [comment]
I highly doubt the symbols returned from the language servers are meant to be used as is, most likely they are used to augment text-based indices like those found in Emacs elsewhere. Therefore, replacing the imenu index directly with whatever is returned from `textDocument/documentSymbol` is highly undesirable.

**Comment by gregnwosu** [comment]
whatever is decided in this dicussion it would be nice if we could retain the option to configure lsp-imenu *once* with individual overrides if deemed necessary. One of the USP's of lsp-mode for me is a generic consistent interface for different language configs

**Comment by myrgy** [comment]
There is imenu limit, which affects presentation https://github.com/emacs-lsp/lsp-mode/issues/329

**Comment by yyoncho** [comment]
After 75d507a9432119f22446114e8921b14f9ebfba65 there is support for hierarchical elements and they could be grouped as per their content, see:

![emacs myoncho_007](https://user-images.githubusercontent.com/13259670/47108156-aeb4c080-d253-11e8-901f-a0711c751996.gif)

Also, each of the languages can set `imenu-create-index-function`  - thus per language configuration is possible even now. @wyuenho can you be a bit more specific what do you expect from `lsp-mode`?

**Comment by yyoncho** [comment]
Closing based on https://github.com/emacs-lsp/lsp-mode/issues/381#issuecomment-430740661 .
