### ISSUE TITLE
Project specific client type

### ISSUE THREAD

**Issue by jennykwan** [emacs-lsp/lsp-mode#397]
LSP seems to be heavily biased towards a single client type (stdio vs. TCP) per language. I do local dev, and I also have some projects that my client company has walled off into devservers (I have limited access to source and don't even know the project's lib deps), which requires TCP.

Right now an `*-enable` function is added to the major mode hook, and that function maps to a hard-selected client. At least, that's the prescribed configuration. It seems to be hard to modify that to work on a per-project basis, i.e. with a `.dir-locals.el` or somesuch.

Would you be open to adding a level of indirection? A macro that wraps the `*-enable` functions and keys them off of unique strings/symbols into a higher-level function (let's call it `*-find-and-enable`) that simply does single dispatch based on the value of a custom var? That custom var could be set in `.dir-locals.el` on a per-project basis, it could fall through to a global for `.emacs`, and failing both of those, the language-specific minor mode could set a default.

What I like about this approach is that it's backwards-compatible. Users continuing to hook into `*-enable` can continue. Users that want per-project customizability can use `*-find-and-enable`.

This is pretty straightforward and I can submit a PR if there's interest.

**Comment by yyoncho** [comment]
you can use the following snippet to define whatever client you want. Then in `your-function` you can use whatever you want to customize on project basis.

``` elisp
(defun your-function ()
  "return whatever you want")

(lsp-define-stdio-client your-lsp-python "python"
			                  (lsp-make-traverser #'(lambda (dir)
						                                   (directory-files
						                                    dir
						                                    nil
                                               "setup.py\\|Pipfile\\|setup.cfg\\|tox.ini")))
			                  nil
                        :command-fn 'your-function)
```

**Comment by vibhavp** [comment]
What do you want to use this for? IMO, it unnecessarily complicates the initialization code.

**Comment by alyssackwan** [comment]
It's fine. It's not very plug and play. I have multiple devices from which I use Emacs and dev from. Plus I have to remember the distinction on a per-project basis stdio vs. TCP, because my employer doesn't allow local checkouts, so I have a devserver for those projects that I have to manually launch an LSP process from (and keep track of ports). This all comes down to stdio not working over Tramp. I understand it's a niche, complicated use case. In essence, I'm extending lsp-mode significantly on my own, and I do agree it's significantly more complex than what's there. If your philosophy is that lsp-mode is more self-service than batteries-included, that's fine.
