### ISSUE TITLE
C: Unable to find any references to a function

### ISSUE THREAD

**Issue by korteland** [emacs-lsp/lsp-mode#4149]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

In a C source file, attempting to find references to a function (right-click the name, then "Find references") yields only the function declaration at point, rather than any uses of the function.

### Steps to reproduce

I used `lsp-start-plain`:

1. `git clone https://github.com/wiredtiger/wiredtiger.git`
2. Open `src/block/block_open.c`
3. Find the function `__wt_block_open`.
4. Right click the function name, and then "Find references".

Note that the `*xref*` buffer only contains one entry, the reference at point. 

### Expected behavior

There are plenty of other users of this function: if you `git grep '__wt_block_open' wiredtiger/src/` you'll see a list like:

```
../src/block/block_open.c: * __wt_block_open --
../src/block/block_open.c:__wt_block_open(WT_SESSION_IMPL *session, const char *filename, uint32_t objectid,
../src/block_cache/block_mgr.c:        WT_ERR(__wt_block_open(session, uri, WT_TIERED_OBJECTID_NONE, cfg, forced_salvage, readonly,
../src/block_cache/block_tier.c:          __wt_block_open(session, object_name, objectid, cfg, false, readonly, false, 0, &block));
../src/block_cache/block_tier.c:          ret = __wt_block_open(session, tmp->mem, objectid, cfg, false, true, true, 0, &block));
../src/include/extern.h:extern int __wt_block_open(WT_SESSION_IMPL *session, const char *filename, uint32_t objectid,
```

I would expect at least some of these to be listed. Interestingly, manually visiting `src/block_cache/block_mgr.c`, then finding the use of `__wt_block_open` and attempting to find references from there yields the reference at point and the definition, but not any of the other references.

### Which Language Server did you use?

clangd

### OS

Linux

### Anything else?

Please let me know if this doesn't repro, or there are more diagnostics or whatever I can provide - I haven't found a workaround for this.

**Comment by necto** [comment]
Hi @korteland 
I am trying to reproduce your issue using lsp-mode with ccls and clangd v18.1.6, Doom Emacs v29.4.

Following your steps, I cloned the project and opened the file in emacs.
1. I've got lsp-mode pop-up and chose to "import project .../wiredtiger" (i.g. the path where I cloned it to)
2. When perusing the files I've got a bunch of errors, most importantly:
    > "wt_internal.h" file not found
    > Too many errors emitted, stopping now
    
Also, in the `*clang::stderr*` buffer, I found

> I[17:43:45.484] Failed to find compilation database for .../wiredtiger/src/block/block_open.c

I believe the problem is with clangd failing to get correct include path list.
To fix that, I generated compilation DB using cmake (see [CMAKE_EXPORT_COMPILE_COMMANDS](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html))

```
wiredtiger $ mkdir build
wiredtiger $ cd build
wiredtiger $ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON . -B build
wiredtiger $ ln -s build/compile_commands.json ./
```

After doing that, I closed all wiredtiger files and reopened src/block/block_open.c
No errors reported this time, and I was able to find multiple uses of `__wt_block_open` (note that clangd might need a bit of time to index files).

Can you try to use compilation DB on your end?

**Comment by korteland** [comment]
Thanks for following up @necto. I followed your steps and it now works fine! I'll close this out as I was using it wrong. https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/ seems to have instructions regarding `compile_commands.json`, so feel free to put it down to users not reading the docs enough.

Thanks once more :-)
