### ISSUE TITLE
Setting lsp-eldoc-render-all to nil can still show multi-line text

### ISSUE THREAD

**Issue by wberrier** [emacs-lsp/lsp-mode#443]
If I customize `lsp-hover-text-function` to use `lsp--text-document-signature-help` I don't get any help documentation.

I've verified this with lsp-python, cquery, and lsp-java

Anyone having `lsp--text-document-signature-help` working?

This is how I have it configured:

```
(use-package lsp-mode
  :custom
  (lsp-hover-text-function (quote lsp--text-document-signature-help))
  )
```

It also doesn't work if I use M-x customize-group and set it through the menus.

**Comment by yyoncho** [comment]
I could speak from `lsp-java` perspective - the JDT server returns the signature only if the code is in () but the `lsp--text-document-signature-help` sends requests only if there is symbol at point. My current workaround is to move the cursor over the function name. `vscode-java` does not show the signature too. It would be good if someone does some research what is the proper way to implement that feature on lsp-mode side since having both signature help and hover does not feel correct.

**Comment by wberrier** [comment]
In checking the protocol interaction between language servers for c++, java, and python, the signatureHelp returns empty results when hovering.

I think the answer I'm looking for is to set `'lsp-eldoc-render-all` to `nil`.  This works great for the java language server, but not for cquery.  The reason is, for the java language server, textDocument/hover returns:

```
Output from language server: {
  "jsonrpc": "2.0",
  "id": 8,
  "result": {
    "contents": [
      {
        "language": "java",
        "value": "void java.io.PrintStream.println(String x)"
      },
      " *  #### println ####\n    \n        public void println(String x)\n    \n    Prints a String and then terminate the line. This method behaves as though it invokes `print(String)` and then `println()`.\n    \n    Parameters:\n    \n    `x` \\- The `String` to be printed."
    ]
  }
}
```

And cquery/c++ language server returns:

```
Output from language server: {
  "jsonrpc": "2.0",
  "id": 84,
  "result": {
    "contents": [
      "\nmatch condition to make sure buffer has at least specified bytes\n\nIntended to be used with async_read_until\n\nConvenient if a buffer is used to read unknow size (ie: http\nheaders) and then known size (ie: content-length body)\n\nOtherwise, the first buffer read may have some data in it, and\nbefore doing the next read, you have to check if the buffer has the\ndata in it already.  Otherwise, you risk doing another read when\nactually all the data has been transferred already.\n\nIt's surprising that asio doesn't provide this match condition already",
      {
        "language": "cpp",
        "value": "std::pair<buffer_iterator_type, bool> webbarrier::asio::match_condition::buffer_contains_at_least(size_t minimum_size, webbarrier::asio::match_condition::buffer_iterator_type begin, webbarrier::asio::match_condition::buffer_iterator_type end)"
      }
    ],
    "range": {
      "start": {
        "line": 12,
        "character": 38
      },
      "end": {
        "line": 12,
        "character": 62
      }
    }
  }
}
```
Notice the ordering the the `contents` array.  I suppose that's why I got the reverse effects in #235 since setting `lsp-eldoc-render-all` to `nil` signifies to only show the first item.

According to the protocol, both responses seem valid.

Thoughts?

**Comment by wberrier** [comment]
Reversing the `contents` array for cquery results in the intended behavior, but `lsp-mode` depending on ordering seems kind of fragile.

**Comment by yyoncho** [comment]
I am not sure what is the correct behaviour. This could be verified by checking how it works in vscode. But anyway this could be fixed by fixing the logic behind `lsp-eldoc-render-all` e. g. take the first item with `language` set you could give it a try.

I am planning to rewrite the on hover code as part of  https://github.com/emacs-lsp/lsp-mode/issues/424 when I get to that since it should merge the hover info from N servers.

**Comment by yyoncho** [comment]
Reversing would break `lsp-java`.

**Comment by wberrier** [comment]
Also note that `pyls` only returns a string, and not a language/value pair (which is still valid):

```
Output from language server: {
  "jsonrpc": "2.0",
  "id": 10,
  "result": {
    "contents": "print(value, ..., sep=' ', end='\\n', file=sys.stdout, flush=False)\n\nPrints the values to a stream, or to sys.stdout by default.\nOptional keyword arguments:\nfile:  a file-like object (stream); defaults to the current sys.stdout.\nsep:   string inserted between values, default a space.\nend:   string appended after the last value, default a newline.\nflush: whether to forcibly flush the stream."
  }
}
```

NOTE: this response currently results in an error: `error in process filter: Wrong type argument: sequencep, 112`

Figuring out a single line to show from these responses seems difficult.  I agree to checking vscode behavior would be helpful.

**Comment by wberrier** [comment]
After looking at the lsp definition, `signatureHelp` is not what we want for eldoc.  It's designed to provide function signature information based on "trigger characters".  (The java ls doesn't support this.)  And cquery supports it based on '(' and ',' trigger characters.

For eldoc, we want thy symbol information for any symbol, not just functions.

So, I think textDocument/hover is the correct request.

@yyoncho I think you are correct in that we should just show what's in the language/value pair.  It's meant to be "code".

Java, cquery, go, rust all "do the right thing" with the language/value pair (python is the only one I could find that didn't, and it should be pretty easy for them to fix).

As an example, `lsp-ui-mode` has `lsp-ui-doc-include-signature` that gets the signature from the language/value and would be appropriate to use for `eldoc`.

Honestly, I think that customizing `lsp-hover-text-function` to use signatureHelp should be disallowed (that's really not what it was meant for) and `lsp-eldoc-render-all` should be removed and always set to `nil` since `eldoc` is intended to just show one line of text.  Users who want the full hover response can do `lsp-describe-thing-at-point` or use lsp-ui-doc.  (My two cents...)

**Comment by yyoncho** [comment]
I agree with what you are proposing, a couple of notes:

1. JDT ls do support signature requests - check SignatureHelpHandler
2. I wrote that ugly code in eldoc when I was adding lsp-eldoc-render-all to keep the backward compatibility. I think that we should remove all the customization (default function, render function...) and do implement the proper language highlighting here in `lsp-mode` instead of forcing the clients to do https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L436 . 
3. We still do need a way to display the document signature, probably after pressing the trigger character. I believe that this must be in eldoc as well and also there should be a command which forces displaying of document signature. (similar to describe one).

I would propose the following action plan:

1. Log a bug for pyls to move the signature as the other server do
2. Fix the error in process filter: Wrong type argument: sequencep, 112 for python
3. Change the code to use the token with language 

Then as part of next release which would include single entry point, multiple servers per workspace we could do the improvements that you have described, this was my action plan from the beginning. I believe that we may keep the render all flag for the users who still want to have that functionality. E. g. cider which is one of the most popular emacs packages do display all the documentation in the eldoc help.

**Comment by wberrier** [comment]
Another sidenote, the eldoc support should honor `eldoc-echo-area-use-multiline-p`

**Comment by wberrier** [comment]
@yyoncho sounds like a good plan.

> JDT ls do support signature requests - check SignatureHelpHandler

Hrm, I thought I saw this disabled in a capabilities request... ok, nevermind.

> Log a bug for pyls to move the signature as the other server do

The pyls issue has been filed here: https://github.com/palantir/python-language-server/issues/439

Thanks!

**Comment by yyoncho** [comment]
@wberrier are you willing to provide PR for 2/3 ?

**Comment by wberrier** [comment]
@yyoncho certainly willing, but I'm a total elisp noob
