### ISSUE TITLE
Unrecognized command or argument 'csharp-ls'

### ISSUE THREAD

**Issue by Empyreans** [emacs-lsp/lsp-mode#4491]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

After entering my C# workspace in Emacs, the lsp server with csharp-lsp immediately exits.

### Steps to reproduce

- setup lsp and use csharp-ls
- open any C# project

### Expected behavior

csharp-ls is working correctly.

### Which Language Server did you use?

csharp-ls

### OS

Windows

### Error callstack
Error Backtrace:

```emacs-lisp
Debugger entered--Lisp error: (error "Unable to find Content-Length header.")
  error("Unable to find Content-Length header.")
  #f(compiled-function (proc input) #<bytecode 0x1336c1cfa0aa6f2a>)(#<process csharp-ls> "Usage: dotnet [runtime-options] [path-to-applicati...")
```

lsp-log:
```
Command "semgrep lsp" is not present on the path.
Command "dotnet  csharp-ls" is present on the path.
Command "semgrep lsp" is not present on the path.
Command "dotnet  csharp-ls" is present on the path.
Found the following clients for c:/Users/empy/git/AzureServiceBusWorker/AzureServiceBusWorker.Main/Worker.cs: (server-id csharp-ls, priority -2)
```

csharp-ls:stderr:
```
Unrecognized command or argument 'csharp-ls'.
Process csharp-ls stderr finished
```

### Anything else?

Most likely related to https://github.com/emacs-lsp/lsp-mode/commit/c69118cc736682e4fa5fad7fb4c840f6daf312e2 ?

**Comment by jcs090218** [comment]
cc @Gastove

**Comment by Gastove** [comment]
I'll have a look very soon here.

**Comment by Empyreans** [comment]
I just reverted back to the older version of `lsp-csharp.el`, that works fine.

**Comment by Gastove** [comment]
Hey @Empyreans! I'd love a bit more information, please. 

- What are (were) your values for `lsp-csharp-csharpls-use-dotnet-tool` and `lsp-csharp-csharpls-use-local-tool`? Did you set either explicitly, or are you using the defaults? 
- Are you installing `csharp-ls` as a dotnet tool? If so, locally or globally? 
- I don't currently have access to a windows machine. Are you game to install from my fork, help make sure this gets fixed? 

My current theory, following the principle, "it's probably ridiculous and I'm probably going to feel extremely silly," is: 

- You're probably using default values, with `csharp-ls` installed as a global tool.
- Turns out, `lsp-csharp--cls-find-executable`, in the default configuration, is returning `("dotnet" "" "csharp-ls")` -- with an empty string in the middle. Eventually, that's passed as the `:command` for `make-process`. 
- On Linux, the empty string is ignored, everything works as I'd expected.
- But on Windows... I'm getting the itchy feeling on Windows, that empty string is fed to `make-process`, and suddenly you're getting the usage string on the `dotnet` CLI instead of language server :facepalm: 

On the upside, if I'm right, the solution is as simple as adding a `-filter` to a function call. Or: I'm wrong, and I've a lot more digging to do.

**Comment by Empyreans** [comment]
I'd love to debug this myself as I'm trying to familiarize myself with elisp, but am currently on a tight schedule.

Of course I'm willing to help: 
- `lsp-csharp-csharpls-use-dotnet-tool` is `t`
- `lsp-csharp-csharpls-use-local-tool` is `nil`
- `csharp-ls` is installed globally as a dotnet tool
- I can try your fork, but I think currently it has no commits

Your theory seems entirely plausible, as the error stacktrace points to an incorrect usage of dotnet.

Edit: I've found the error.
On Windows we should neither call `("dotnet" "" "csharp-ls")` nor `("dotnet" "csharp-ls")` but only `("csharp-ls")`!

**Comment by jcs090218** [comment]
Feel free to open a PR for this! :D

**Comment by Gastove** [comment]
@Empyreans gaaaah, you're right! My apologies -- I misread the docs on that one :facepalm: That _should_ work on not-windows too. 

We'll see which of us gets the PR up :laughing: Thanks for the help!
