### ISSUE TITLE
Lsp Hover causes desktop spaces  to be switched to the previous one on MacOs Sequoia

### ISSUE THREAD

**Issue by ScriptMang** [emacs-lsp/lsp-mode#4552]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [x] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I'm getting an issue where the current virtual desktop space I have emacs in, keeps switching back to the previous one. In particular after every code completion from corfu when emacs is fullscreen. Or when lsp mode shows function definitions on hover in fullscreen. No error is produced in the message or warning buffer. However, if I set the app not to launch on a specific desktop, it doesn't happen. Currently I'm using emacs-plus@29(29.4) and elpaca as my pkg manager. The lsp mode I used was
gopls for go files.  

### Steps to reproduce

MacOs Sequoia must be installed
right click on emacs after launch and click on "set this desktop"
set emacs to fullscreen and open a programming file
activate lsp mode and hover over function

### Expected behavior

My expectation is on hover lsp mode doesn't change desktop focus from fullscreen emacs.

### Which Language Server did you use?

I used gopls 

### OS

MacOS

**Comment by certainty** [comment]
I experience the same. However I do not think it is LSP related. I use eglot. It is probably emacs itself and corfu . IIRC the corfu overlay is a frame. Maybe there are weird interactions with macOS window handling. Which emacs build are you using?

**Comment by ScriptMang** [comment]
emacs plus  29.4-1

**Comment by ScriptMang** [comment]
https://github.com/d12frosted/homebrew-emacs-plus

**Comment by david-krentzlin** [comment]
Thanks. So I did a bit of experimentation and at least for me, the switch happens only after I switch the frame to fullscreen. And it happens only once after that. So the experiment to try is. 

1. Open emacs (not in fullscreen)
2. Try complete => it should not switch away
3. Bring emacs to fullscreen 
4. Try complete => switch to different desktop
5. Try complete again => no switch anymore

I have a hunch that corfu misplaces the childframe because for some reason it doesn't know the correct dimensions of the emacs frame. So it maybe places it to the left of a fullscreen window which makes the window manager of OSX switch to a different desktop.

Again, none of this is lsp-mode related in my mind, but I wanted to comment here for completeness. 
I am still trying to find a solution myself (with hopefully not too much effort).

**Comment by david-krentzlin** [comment]
As a workaround instead of putting emacs into fullscreen you can put emacs into maximized state, which doesn't have this problem.

**Comment by ScriptMang** [comment]
The way I managed to work around this was removing the application's assignment to a virtual desktop window. After that I no longer experience the issue.
