### ISSUE TITLE
Not all methods in company dropdown using the Microsoft Python LS

### ISSUE THREAD

**Issue by astenman** [emacs-lsp/lsp-mode#518]
Please ask your questions at https://gitter.im/emacs-lsp/lsp-mode

I don't know if I am doing something wrong, but for some Python objects I do not get any methods in the company dropdown. In VS Code, which uses the same LS, it works better ...
![dump](https://user-images.githubusercontent.com/43724994/49689777-81371580-fb26-11e8-87c5-fa6799c1cf44.png)

**Comment by yyoncho** [comment]
Can you share language configuration + the content of Messages buffer with lsp-print-io set to t?

**Comment by cpbotha** [comment]
@astenman I wrote this: https://vxlabs.com/2018/11/19/configuring-emacs-lsp-mode-and-microsofts-visual-studio-code-python-language-server/

If you don't do the config exactly right, you will indeed see that difference between your emacs setup and vs.code.

We are busy turning that blog post into an emacs package: https://github.com/andrew-christianson/lsp-python-ms

Status: Currently broken due to recent breaking (haha) changes in lsp-mode. Will try to fix in new year.

**Comment by cpbotha** [comment]
@astenman Durr, I see you have already submitted a PR to the package, awesome!

**Comment by yyoncho** [comment]
Closing based on https://github.com/emacs-lsp/lsp-mode/issues/518#issuecomment-450024153 .
