### ISSUE TITLE
Project root detection logic : auto-guess-root 'ignored' in nested projects

### ISSUE THREAD

**Issue by gagbo** [emacs-lsp/lsp-mode#533]
**Describe the bug**
I can have different values from `(projectile-project-root)` and `(lsp-workspace-root)` even with `lsp-auto-guess-root` to `t`

**To Reproduce**
I know there's a git clone, but it's small, and no code at all needs to be ran

- clone this small advent of code repo : [gagbo/advent-of-code_2018](https://github.com/gagbo/advent-of-code_2018), which is a collection of small LSP workspaces
- `touch 08/day08-rs/.projectile` to tell projectile that this folder a project
- Open emacs on `08/day08-rs/src/main.rs`
- start `(lsp)` (done in a rust-mode-hook for me)

**Expected behavior**
`(lsp-workspace-root)` returns `.../advent-of-code_2018/08/day08-rs`

**Which Language Server did you use**
bundled rls in lsp-clients

**Note**
I suppose the issue is that [try-open-in-library-workspaces](https://github.com/emacs-lsp/lsp-mode/blob/c0d1192a7ae725b924e9ce7540226c38a0d3e35c/lsp.el#L3400) returns a result and this one is used instead of asking for the guess root

**OS**
Fedora rawhide

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of \*Messages\* buffer.

Since `(lsp-workspace-root)` does not have the correct value, rls keeps spamming error messages because it doesn't look for Cargo.toml in the correct location (a few lines from rls buffer) : 
```
ERROR 2018-12-12T03:03:22Z: rls::actions: failed to fetch project model, using fallback: failed to read `/home/gagbo/projects/advent-of-code_2018/Cargo.toml`
ERROR 2018-12-12T03:03:22Z: rls::actions: failed to fetch project model, using fallback: failed to read `/home/gagbo/projects/advent-of-code_2018/Cargo.toml`
ERROR 2018-12-12T03:03:22Z: rls::actions: failed to fetch project model, using fallback: failed to read `/home/gagbo/projects/advent-of-code_2018/Cargo.toml`
```

**Comment by yyoncho** [comment]
`lsp-auto-guess-root` is intended to be used only if you have plain project structure and only if you can debug/fix autodetection because projectile/project.el could be tricky. Here it is how to import nested projects:

1. Have default configuration of lsp-mode.el (e. g. `lsp-auto-guess-root` set to nil)
2. Delete the file that is storing the session to start fresh (`lsp-session-file`). To ensure the session is empty do lsp-describe-session
3. Open the rs file you have mentioned
4. From the menu select second option: "Import project by selecting root directory interactively."
5. Select the folder the root folder for the rust project.
