### ISSUE TITLE
[mouse]  Right click support  for lsp-mode

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#564]
1. Right click support
2. Ctrl + click - to follow references
3. ?

**Comment by mcraveiro** [comment]
@yyoncho,

As discussed in Gitter, I had bumped into a mode in Emacs which transformed include statements into links, very much like a HTTP link or a org-mode link. As a result, the include file would show up underlined. I could then follow these links. Sadly (and somewhat comically) I'm not sure what mode gave me this functionality and it went away so I can't screenshot it, but when I did have it, it was extremely useful.

**Comment by leungbk** [comment]
```emacs-lisp
(defun lsp-find-definition-mouse (click)
  "Click to start `lsp-find-definition' at clicked point."
  (interactive "e")
  (let ((p1 (posn-point (event-start click))))
    (goto-char p1)
    (lsp-find-definition)))

(define-key lsp-mode-map (kbd "<mouse-3>") #'lsp-find-definition-mouse)
```

This is largely the same as something I saw on Xah Lee's blog. I'm using something like this in my own config but I call `xref-find-foo` with the appropriate backend info instead of `lsp-find-foo`. Might be worth a PR? If so, I'm not sure if I need to worry about the `:display-action` key that many of the `lsp-find-foo`s use.

**Comment by yyoncho** [comment]
@leungbk sounds good, except for the keybinding -  In most GUI IDEs go to definition is bound to Ctrl-Click, IMO it makes sense to do the same in lsp-mode.
