### ISSUE TITLE
Rust support not working out of box

### ISSUE THREAD

**Issue by otavio** [emacs-lsp/lsp-mode#581]
My current setup uses `lsp-mode` and `rustic-mode`. So far, I am quite happy with it, in general.

I've been keeping it all updated and always trying to remove the workarounds I had to do to get it going. I still have one:

```emacs-lisp
(unless (fboundp 'lsp-rust-enable)
  (defun lsp-rust-enable ()
    ()))
```

Without this block, RLS does not get started. Please let me know if you need any information, so I can gather it and post it here.

**Comment by yyoncho** [comment]
Please share your full `lsp` related configuration? In general, `lsp-rust-enable` must be replaced with call to `lsp`.

**Comment by otavio** [comment]
Please take a look at https://github.com/otavio/.emacs.d/blob/39bcdef55fbd5517bce545729496d83f324cb7bf/lisp/init-rust.el#L17

This has my full setup.

**Comment by Compro-Prasad** [comment]
Same with me.

**Comment by Compro-Prasad** [comment]
I also get the following when I call `M-x lsp-goto-type-definition` on an identifier:
```
lsp-goto-type-definition: Capability not supported by the language server: "typeDefinitionProvider"
```

**Comment by yyoncho** [comment]
@otavio rustic-mode is not synched with the latest lsp-mode release - https://github.com/brotzeit/rustic/blob/4db16c2f7782b441e689d1469de012d32a2fe838/rustic-util.el#L196 `lsp-rust-enable` -> `lsp` . Also, I encourage you to go through the latest lsp-mode readme since most of your configuration is no longer needed.

@Compro-Prasad 
> lsp-goto-type-definition: Capability not supported by the language server: "typeDefinitionProvider"

RLS does not support typeDefinition requests so you get an error when you try unsupported feature.
