### ISSUE TITLE
Buffer name convention

### ISSUE THREAD

**Issue by gahag** [emacs-lsp/lsp-mode#583]
The name of the buffers created by lsp.el is not enclosed in asterisks. This convention was used before, and I used a regex with that to hide those buffers from my buffers list.

How to reproduce:
Start lsp.el with a language server, e.g. python, and observe the existence of a buffer named "pyls", instead of "\*pyls\*".

**Comment by seagle0128** [comment]
I vote this. The buffer names are annoying. If I want to restore the sessions, many lsp buffers are recovered, because I don't know how to filter them. NO name convention, NO special major mode. I tried to use regexp, but failed. Think about this: `go-ls`, `go-bingo`, `pyls`, `ts-ls`, etc.  How should I do? 

I think maybe `*go-ls*`, `*pyls*`, `ts-ls*` are better name, and/or special mode for these buffers while not `fundamental-mode`.

**Comment by gahag** [comment]
I used this before to filter the lsp buffers from helm:
```
(setq helm-boring-buffer-regexp-list '(
...
"\\`\\*lsp"
...
))
```

**Comment by yyoncho** [comment]
I have wrapped the buffer names with * as per emacs buffer naming convention.

**Comment by seagle0128** [comment]
Thank you, @yyoncho .
