### ISSUE TITLE
Stored projects are opened in order

### ISSUE THREAD

**Issue by karstenpatzwaldt** [emacs-lsp/lsp-mode#760]
**Describe the bug**
When opening a project through tramp (e.g., /ssh:hostname:path/to/source.c), and adding the project to LSP, the project will be stored in ~/.emacs/.lsp-session-v1. Later, when moving to a different network, and opening a different project, lsp-mode will try to connect to the remote repo first, which may not be accessible at that time.

**To Reproduce**
1. Configure any LSP server for tramp (e.g. clangd)
2. Open a remote project that is supported by the configured server (e.g. /ssh:hostname:path/to/source.c)
3. When prompted, confirm to create the project - lsp-mode will add an entry to ~/.emacs/.lsp-session-v1
4. Open another local project (i.e. not through tramp)
5. When prompted, confirm to create the project
6. Close emacs
7. Disconnect network
8. Open emacs
9. Open the second, local project again
10. lsp-mode will go through the project list, and open them in order. If any of the projects are remote and not reachable at that time, lsp-mode will open the tramp connection, fail to do so, and then fail to open the local project

**Expected behavior**
I should be able to open local projects, even if I opened tramp projects before that may not be reachable anymore.

**Which Language Server did you use**
clangd

**OS**
Ubuntu 18.10

**Comment by magonreal** [comment]
I am facing the same problem.
It's annoying because I have lots of projects which I want to work on over tramp, and still want to use my local files without clearing the projects manually every time. Especially, because I need VPN to access the server, emacs just freezes trying to connect to it and fails.

Is it possible to add a setting to the lsp-mode "import project root" to just temporary add a project and remove it when quitting? It would be convenient to have it there permanently, but still more convenient than deleting the remote project folders manually every time.
