### ISSUE TITLE
lsp-file-watch-ignored  is not sufficient to prevent file notifications

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#805]
Given the following project structure:

```
root/
  src/
    app/
      .project
      src/ <- should be watched
      tst/ <- ditto
      build/ <- should be ignored
```

Adding `build` to the ignored files does not avoid the file notifications.

(cc @aureumleonis )

**Comment by aureumleonis** [comment]
To give more context build is a symlink which is deleted and re-created when a build tool is run

**Comment by aureumleonis** [comment]
I've been able to prevent the notifications by applying the filter once again within `lsp--file-process-event`.

**Comment by madscientist** [comment]
FYI what I'm seeing is that directories created after the initial project root has been watched, are not filtered by `lsp-file-watch-ignored`.  So for example if I have added the string `"\\.foo"` to my ignored list and I have a directory `aaa.foo` that exists before I start emacs, then when I start emacs and visit a file in that project I can see it does _not_ watch `aaa.foo` (as I expect).

However, if while that emacs is running I add a new directory via `mkdir bbb.foo`, then I can see (both through the `*lsp-mode*` buffer and also by looking at `(ht-valuse (lsp-session-watches (lsp-session)))`) that `bbb.foo` is being watched, when it shouldn't be.

I believe the problem is the recursion in `lsp-watch-root-folder`: it seems to work by (a) watch the passed-in dir, then (b) look at all the subdirectories and recurse on any that match the ignored list.  This means that the first directory is _always_ watched even if it should be ignored.

I think this recursion has to be changed to be: (a) check the passed-in dir and if it's ignored just return, else (b) watch it, then recurse on all subdirectories.

By pushing the check into the recursive call, instead of avoiding the recursion if it matches, you'll be sure to apply that check to the initial dir as well.  My elisp fu has withered significantly so I'm not planning on looking at this for now.  If no one else can find the time I might get around to it in a few weeks.

**Comment by aureumleonis** [comment]
I fixed this locally but I've been procrastinating and haven't submitted a PR yet. I'll try to do it today

**Comment by madscientist** [comment]
Is this something we can fix?  I've been bit by this over and over, because my test suite creates temporary files in the "tmp" directory in the root of my project, and my Emacs goes bananas trying to watch them all.

**Comment by yyoncho** [comment]
There is PR at https://github.com/emacs-lsp/lsp-mode/pull/830

**Comment by madscientist** [comment]
w00t!  Thanks!  Hopefully will appear in elpa soon-ish.
