### ISSUE TITLE
more efficient conversion of point to lsp position 

### ISSUE THREAD

**Issue by muirdm** [emacs-lsp/lsp-mode#948]
**Describe the bug**
After opening a large file (github.com/aws/aws-sdk-go/service/s3/api.go) my Emacs becomes unresponsive, using 100% CPU. I tried waiting a minute, but it didn't seem to recover.

**To Reproduce**
Open above file and run `lsp`.

**Expected behavior**
I expected Emacs to work normally.

**Which Language Server did you use**
gopls

**OS**
Mac

**Error callstack**
I set `debug-on-quit` and got a stack trace:

https://gist.github.com/muirrn/40a9a4782c7e07c50c58bdcfe693bcca

**Comment by yyoncho** [comment]
Confirmed - the issue seems to be related to imenu position->point conversion. I tested with lsp-treemacs symbols view and it works very fast but only if I disable the automatic expand when opening(which is very slow).

**Comment by yyoncho** [comment]
Pushed https://github.com/emacs-lsp/lsp-mode/commit/fcd2d0cdae18e87501488e10e8d6bc3d55754e26 . The result is that the imenu won't be refreshed if you do not have menu-bar-mode enabled. This document has 3000+ symbols and it is 25k lines long and in order to convert (line, character) to (point). Our code is like that:

```
(goto-char (point-min))
            (forward-line line)
            (forward-char character)
            (point)
```

which pretty much means that we start from the beginning of the buffer and scan N lines. I think that we could optimize by keeping the current position and starting from that point which will eventually decrease the number of lookups. Or even we could scan the file new once and cache the points at which the lines start and then use that as a index to optimize the lookup.

**Comment by muirrn** [comment]
I can confirm the change prevents the problem. Do you want me to close or keep it open to track further improvements?

**Comment by yyoncho** [comment]
The problem is only delayed. Once you do helm-imenu or related else you still will wait for 1+ minutes. I will leave it open, but won't be addressed with priority due to the fact that there is a workaround. Marking it with "Help needed".
